/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 16 10:46:42 GMT 2025
 */

package org.apache.commons.math4.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.util.FastMath;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FastMath_ESTest extends FastMath_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      float float0 = FastMath.copySign((float) 2415L, (float) 837);
      assertEquals(2415.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      double double0 = FastMath.copySign(0.3333333333333333, 0.3333333333333333);
      assertEquals(0.3333333333333333, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      long long0 = FastMath.floorMod((long) 16, 4294967295L);
      assertEquals(16L, long0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      int int0 = FastMath.floorMod(2111085620, 3);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      long long0 = FastMath.floorDiv(1L, (-5034868814120038111L));
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      long long0 = FastMath.floorDiv((long) (-1466), (long) (-1466));
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      int int0 = FastMath.floorDiv(11, (-2383));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      long long0 = FastMath.multiplyExact(0L, (-9223372036854775808L));
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      long long0 = FastMath.multiplyExact(2L, (-3958705157555305932L));
      assertEquals((-7917410315110611864L), long0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      long long0 = FastMath.multiplyExact(2935890503282001226L, 0L);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      int int0 = FastMath.multiplyExact((-1), (-2040109465));
      assertEquals(2040109465, int0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      int int0 = FastMath.multiplyExact(1, (-2146846869));
      assertEquals((-2146846869), int0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.subtractExact(0L, (-9223372036854775808L));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in subtraction: 0 - -9,223,372,036,854,775,808
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      long long0 = FastMath.addExact(4503599627370496L, 4503599627370455L);
      assertEquals(9007199254740951L, long0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      int int0 = FastMath.toIntExact(Integer.MAX_VALUE);
      assertEquals(Integer.MAX_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      int int0 = FastMath.toIntExact((-2147483648L));
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      double double0 = FastMath.hypot((-2.2113260264401537), 2.925681159240093E-8);
      assertEquals(2.2113260264401537, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      long long0 = FastMath.max(2256L, 3563L);
      assertEquals(3563L, long0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      long long0 = FastMath.min((-536L), 0L);
      assertEquals((-536L), long0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      double double0 = FastMath.rint((-1730.2));
      assertEquals((-1730.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      double double0 = FastMath.rint(0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      double double0 = FastMath.IEEEremainder((-4.503599627370496E15), 1.0);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      double double0 = FastMath.ceil(4.503599627370496E15);
      assertEquals(4.503599627370496E15, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      float float0 = FastMath.scalb((-4012.8F), (-138));
      assertEquals((-1.1516172E-38F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      float float0 = FastMath.scalb(768.35376F, (-277));
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      float float0 = FastMath.scalb((float) (-127), (-127));
      assertEquals((-7.464389E-37F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      double double0 = FastMath.scalb(6.490658607289271, 2097);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      double double0 = FastMath.scalb(3921.197, (-2098));
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      double double0 = FastMath.scalb(3.0095696449279785, 1024);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      float float0 = FastMath.ulp((-2227.6907F));
      assertEquals(2.4414062E-4F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      int int0 = FastMath.abs((-2486));
      assertEquals(2486, int0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      double double0 = FastMath.cbrt((-4.9E-324));
      assertEquals((-1.7031839360032603E-108), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      double double0 = FastMath.asin(0.036);
      assertEquals(0.036007780538464686, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      double double0 = FastMath.atan2(0.0, 0.45538831849139333);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      double double0 = FastMath.acos(6.123233995736766E-17);
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      double double0 = FastMath.tan((-1.5707963267948966));
      assertEquals((-1.633123935319537E16), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      double double0 = FastMath.tan(3294198.0);
      assertEquals((-0.7734333808731876), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      double double0 = FastMath.cos(1.5707963267948966);
      assertEquals(6.123233995736766E-17, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      double double0 = FastMath.cos(0.0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      double double0 = FastMath.sin((-1.5707963267948966));
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      double double0 = FastMath.sin(3294198.0);
      assertEquals((-0.6117971622964877), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      double double0 = FastMath.pow((-2281.9066742), (-9223372036854775808L));
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      double double0 = FastMath.pow(Double.NEGATIVE_INFINITY, (double) 7910884519577875640L);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      double double0 = FastMath.log1p((-1.0E-6));
      assertEquals((-1.0000005000003334E-6), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      double double0 = FastMath.log1p(1.0E-6);
      assertEquals(9.999995000003334E-7, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      double double0 = FastMath.expm1(1.0);
      assertEquals(1.7182818284590453, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      double double0 = FastMath.expm1((-1L));
      assertEquals((-0.6321205588285577), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      double double0 = FastMath.exp((-746.0));
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      double double0 = FastMath.signum(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      double double0 = FastMath.atanh(0.15);
      assertEquals(0.15114043593646678, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      double double0 = FastMath.asinh(0.167);
      assertEquals(0.1662333393520369, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      double double0 = FastMath.tanh(0.5F);
      assertEquals(0.46211715726000974, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      double double0 = FastMath.tanh((-20.0));
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      double double0 = FastMath.tanh(20.0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      double double0 = FastMath.sinh((-709.782712893384));
      assertEquals((-8.988465674311366E307), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      double double0 = FastMath.sinh(20.0);
      assertEquals(2.4258259770489514E8, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      double double0 = FastMath.cosh(0.0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      double double0 = FastMath.cosh((-709.782712893384));
      assertEquals(8.988465674311366E307, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      double double0 = FastMath.cosh((-20.0));
      assertEquals(2.4258259770489514E8, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      double double0 = FastMath.cosh(709.782712893384);
      assertEquals(8.988465674311366E307, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      double double0 = FastMath.cosh(20.0);
      assertEquals(2.4258259770489514E8, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      double double0 = FastMath.atan2(1.0314130998795732, 2.2250738585072014E-308);
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      double double0 = FastMath.toRadians((-2.2250738585072014E-308));
      assertEquals((-3.8834864931005E-310), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      int int0 = FastMath.toIntExact(0L);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      double double0 = FastMath.toDegrees((-2484.1042345132));
      assertEquals((-142328.68850818244), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      long long0 = FastMath.subtractExact(0L, 5648769086999809661L);
      assertEquals((-5648769086999809661L), long0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      int int0 = FastMath.subtractExact(1137, 2145887353);
      assertEquals((-2145886216), int0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      double double0 = FastMath.sqrt(0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      int int0 = FastMath.round(2416.0F);
      assertEquals(2416, int0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      int int0 = FastMath.round((-3.4028235E38F));
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      long long0 = FastMath.round(0.19999998807907104);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      long long0 = FastMath.round((double) (-3183605296591799669L));
      assertEquals((-3183605296591799808L), long0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      double double0 = FastMath.rint((-89.5));
      assertEquals((-90.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      double double0 = FastMath.pow((double) (-2089.2683F), 2047L);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      double double0 = FastMath.pow((-2606.6755115808), (double) 1.0F);
      assertEquals((-2606.6755115808), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      float float0 = FastMath.nextUp((-1.4E-45F));
      assertEquals(-0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      double double0 = FastMath.nextUp((-4.9E-324));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      float float0 = FastMath.nextDown(1.4E-45F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      float float0 = FastMath.nextAfter((float) 0, 0.0);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      double double0 = FastMath.nextAfter(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      long long0 = FastMath.multiplyExact((long) 0, (long) 128);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      int int0 = FastMath.multiplyExact((-3557), 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      int int0 = FastMath.multiplyExact((-1), 1073741833);
      assertEquals((-1073741833), int0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      long long0 = FastMath.min(0L, (long) 0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      int int0 = FastMath.min(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      long long0 = FastMath.max((long) 0, 0L);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      int int0 = FastMath.max(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      int int0 = FastMath.max((-1466), (-127));
      assertEquals((-127), int0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      float float0 = FastMath.max((-1.0F), (float) (-1023));
      assertEquals((-1.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      double double0 = FastMath.log1p(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      double double0 = FastMath.log10(1.0F);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      double double0 = FastMath.log(0.0, 6.567779607147072E-182);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      double double0 = FastMath.log(0.8774870922830788, 0.018315639346837997);
      assertEquals(30.606068823652667, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      double double0 = FastMath.log(1.7827257129423813E-8, 1.2599210311205868);
      assertEquals((-0.0129493379797341), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      double double0 = FastMath.log((double) 2415L);
      assertEquals(7.789454566086673, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      double double0 = FastMath.log(0.0);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      long long0 = FastMath.incrementExact((long) (-1));
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      long long0 = FastMath.incrementExact((long) (-2486));
      assertEquals((-2485L), long0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      int int0 = FastMath.incrementExact((-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      int int0 = FastMath.incrementExact((-1846));
      assertEquals((-1845), int0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      int int0 = FastMath.getExponent((-1.0F));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      int int0 = FastMath.getExponent((float) (-2728));
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      int int0 = FastMath.getExponent(1.5);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      int int0 = FastMath.getExponent(0.0);
      assertEquals((-1023), int0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      long long0 = FastMath.floorMod(2147483648L, (-2527L));
      assertEquals((-1384L), long0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      int int0 = FastMath.floorMod(9, (-2383));
      assertEquals((-2374), int0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      long long0 = FastMath.floorDiv(2415L, 4368491638549381120L);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      int int0 = FastMath.floorDiv((-314), (-539));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      long long0 = FastMath.decrementExact((long) 1);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      long long0 = FastMath.decrementExact((long) (-1213));
      assertEquals((-1214L), long0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      int int0 = FastMath.decrementExact(1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      int int0 = FastMath.decrementExact(1921);
      assertEquals(1920, int0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      float float0 = FastMath.copySign(1.5258789E-5F, 1.5258789E-5F);
      assertEquals(1.5258789E-5F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      double double0 = FastMath.copySign((double) 0, 1.6844747839686189E-9);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      double double0 = FastMath.ceil((-97.3350639));
      assertEquals((-97.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      double double0 = FastMath.atanh(-0.0F);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      double double0 = FastMath.atanh((-0.2499999701976776));
      assertEquals((-0.2554127800938517), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      double double0 = FastMath.atan(0L);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      double double0 = FastMath.atan(1848.463254517);
      assertEquals(1.5702553369212815, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      long long0 = FastMath.addExact((long) 0, (long) 0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      int int0 = FastMath.addExact(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      int int0 = FastMath.addExact(3262, 2783);
      assertEquals(6045, int0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      double double0 = FastMath.acosh(1L);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      double double0 = FastMath.acosh(8.782487532752182E195);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      double double0 = FastMath.acosh((-2146880082));
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      long long0 = FastMath.abs(0L);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      long long0 = FastMath.abs((-9223372036854775808L));
      assertEquals((-9223372036854775808L), long0);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      int int0 = FastMath.abs(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      float float0 = FastMath.abs(3002.4224F);
      assertEquals(3002.4224F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      double double0 = FastMath.abs(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      double double0 = FastMath.IEEEremainder(545.0676218447829, 4.23719669792332E-8);
      assertEquals((-8.71909833222162E-9), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      double double0 = FastMath.copySign(5.858546779607288E-181, (-2142.632675100189));
      assertEquals((-5.858546779607288E-181), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      double double0 = FastMath.rint(536.04749207);
      assertEquals(536.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      double double0 = FastMath.rint((-4.768920119497491E-8));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      double double0 = FastMath.floor(0.5);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      double double0 = FastMath.floor((-1.5707963267948966));
      assertEquals((-2.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      double double0 = FastMath.floor((-3.1836052965917998E18));
      assertEquals((-3.1836052965917998E18), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      double double0 = FastMath.floor(4.730212475795673E288);
      assertEquals(4.730212475795673E288, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      double double0 = FastMath.floor(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      float float0 = FastMath.nextAfter(0.5F, (-3566.70933));
      assertEquals(0.49999997F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      float float0 = FastMath.nextAfter(1.0F, 4002.6);
      assertEquals(1.0000001F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      float float0 = FastMath.nextAfter(0.0F, (-1420.7023321440615));
      assertEquals((-1.4E-45F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      float float0 = FastMath.nextAfter((-895.7F), (-4098.857127));
      assertEquals((-895.7001F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      float float0 = FastMath.nextAfter(Float.POSITIVE_INFINITY, (-1.0126616322947826E158));
      assertEquals(3.4028235E38F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      float float0 = FastMath.nextAfter(Float.NEGATIVE_INFINITY, 7.596201897584845E26);
      assertEquals((-3.4028235E38F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      float float0 = FastMath.nextAfter(Float.NaN, (-1874.897425200112));
      assertEquals(Float.NaN, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      float float0 = FastMath.nextAfter(-0.0F, 3660.08402923);
      assertEquals(1.4E-45F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      double double0 = FastMath.nextAfter((double) (-779L), (double) 1L);
      assertEquals((-778.9999999999999), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      double double0 = FastMath.nextAfter((-0.6321205588285577), (double) (-1L));
      assertEquals((-0.6321205588285578), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      double double0 = FastMath.nextAfter(0.0, (double) (-1499.31F));
      assertEquals((-4.9E-324), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      double double0 = FastMath.nextAfter(0.0, 3.9761438806369426E165);
      assertEquals(4.9E-324, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      double double0 = FastMath.nextAfter(Double.POSITIVE_INFINITY, (double) 512L);
      assertEquals(1.7976931348623157E308, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      double double0 = FastMath.nextAfter(662.6776628199689, (-1.0E-6));
      assertEquals(662.6776628199688, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      double double0 = FastMath.scalb(0.0, (-3557));
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      double double0 = FastMath.scalb(3635.881, 289);
      assertEquals(3.616416212241703E90, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      double double0 = FastMath.pow(1.7827257129423816E-8, (long) 0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      double double0 = FastMath.sqrt(1.356201171875);
      assertEquals(1.1645605058883801, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      int int0 = FastMath.getExponent((-58.95722213236845));
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      float float0 = FastMath.abs(0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      double double0 = FastMath.abs(2634.1281141507);
      assertEquals(2634.1281141507, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      double double0 = FastMath.sin(3.141592653589793);
      assertEquals(1.2246467991473532E-16, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      float float0 = FastMath.copySign(0.0F, 0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      float float0 = FastMath.copySign((float) 382L, -0.0F);
      assertEquals((-382.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test163()  throws Throwable  {
      long long0 = FastMath.floorMod(0L, (-3958705157555305932L));
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test164()  throws Throwable  {
      long long0 = FastMath.floorMod((-560L), 8435453208297472L);
      assertEquals(8435453208296912L, long0);
  }

  @Test(timeout = 4000)
  public void test165()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.floorMod(11072475434399490L, 0L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // denominator must be different from 0
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test166()  throws Throwable  {
      long long0 = FastMath.floorMod((-2875L), (-2875L));
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test167()  throws Throwable  {
      int int0 = FastMath.floorMod((-1656), 4);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test168()  throws Throwable  {
      int int0 = FastMath.floorMod((-4083), 3360);
      assertEquals(2637, int0);
  }

  @Test(timeout = 4000)
  public void test169()  throws Throwable  {
      try { 
        FastMath.floorMod((-2131), 0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // denominator must be different from 0
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test170()  throws Throwable  {
      int int0 = FastMath.floorMod(1464, 1464);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test171()  throws Throwable  {
      long long0 = FastMath.floorDiv((long) (-1466), 1L);
      assertEquals((-1466L), long0);
  }

  @Test(timeout = 4000)
  public void test172()  throws Throwable  {
      long long0 = FastMath.floorDiv((-2328L), (long) 982199681);
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test173()  throws Throwable  {
      try { 
        FastMath.floorDiv(4503599627370496L, 0L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // denominator must be different from 0
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test174()  throws Throwable  {
      int int0 = FastMath.floorDiv((-1304), 1);
      assertEquals((-1304), int0);
  }

  @Test(timeout = 4000)
  public void test175()  throws Throwable  {
      int int0 = FastMath.floorDiv((-3774), 412);
      assertEquals((-10), int0);
  }

  @Test(timeout = 4000)
  public void test176()  throws Throwable  {
      try { 
        FastMath.floorDiv(0, 0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // denominator must be different from 0
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test177()  throws Throwable  {
      int int0 = FastMath.floorDiv(135, 135);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test178()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.multiplyExact((-3183605296591799669L), (-11072475434399490L));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in multiplication: -3,183,605,296,591,799,669 * -11,072,475,434,399,490
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test179()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.multiplyExact(4503599627370496L, (-2644281811660520851L));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in multiplication: 4,503,599,627,370,496 * -2,644,281,811,660,520,851
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test180()  throws Throwable  {
      long long0 = FastMath.multiplyExact((-29L), (-29L));
      assertEquals(841L, long0);
  }

  @Test(timeout = 4000)
  public void test181()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.multiplyExact(9154082963658188193L, 9154082963658188193L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in multiplication: 9,154,082,963,658,188,193 * 9,154,082,963,658,188,193
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test182()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.multiplyExact((-594L), 4368491638549381114L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in multiplication: -594 * 4,368,491,638,549,381,114
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test183()  throws Throwable  {
      long long0 = FastMath.multiplyExact((-1L), (-1L));
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test184()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.multiplyExact(Integer.MIN_VALUE, Integer.MIN_VALUE);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in multiplication: -2,147,483,648 * -2,147,483,648
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test185()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.multiplyExact(2145059757, (-199));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in multiplication: 2,145,059,757 * -199
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test186()  throws Throwable  {
      int int0 = FastMath.multiplyExact(1, 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test187()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.multiplyExact(1700, 2147483583);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in multiplication: 1,700 * 2,147,483,583
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test188()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.multiplyExact((-277), 2130706432);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in multiplication: -277 * 2,130,706,432
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test189()  throws Throwable  {
      int int0 = FastMath.multiplyExact((-1), (-1));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test190()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.subtractExact((-2031L), 9223372036854775801L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in subtraction: -2,031 - 9,223,372,036,854,775,801
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test191()  throws Throwable  {
      long long0 = FastMath.subtractExact(157L, (-1073741824L));
      assertEquals(1073741981L, long0);
  }

  @Test(timeout = 4000)
  public void test192()  throws Throwable  {
      long long0 = FastMath.subtractExact((-2644281811660520851L), (-2644281811660520851L));
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test193()  throws Throwable  {
      int int0 = FastMath.subtractExact(750, (-2146624968));
      assertEquals(2146625718, int0);
  }

  @Test(timeout = 4000)
  public void test194()  throws Throwable  {
      // Undeclared exception!
      try { 
        FastMath.subtractExact(2078, (-2147483646));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in subtraction: 2,078 - -2,147,483,646
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test195()  throws Throwable  {
      int int0 = FastMath.subtractExact(52, 52);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test196()  throws Throwable  {
      try { 
        FastMath.addExact(9223372036854775807L, 9223372036854775807L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in addition: 9,223,372,036,854,775,807 + 9,223,372,036,854,775,807
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test197()  throws Throwable  {
      long long0 = FastMath.addExact((-89L), (-89L));
      assertEquals((-178L), long0);
  }

  @Test(timeout = 4000)
  public void test198()  throws Throwable  {
      long long0 = FastMath.addExact(4503599627370496L, (-3340L));
      assertEquals(4503599627367156L, long0);
  }

  @Test(timeout = 4000)
  public void test199()  throws Throwable  {
      try { 
        FastMath.addExact(2137722358, 2145620924);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in addition: 2,137,722,358 + 2,145,620,924
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test200()  throws Throwable  {
      int int0 = FastMath.addExact((-1213), (-1213));
      assertEquals((-2426), int0);
  }

  @Test(timeout = 4000)
  public void test201()  throws Throwable  {
      int int0 = FastMath.addExact(64, (-426));
      assertEquals((-362), int0);
  }

  @Test(timeout = 4000)
  public void test202()  throws Throwable  {
      try { 
        FastMath.decrementExact((-9223372036854775808L));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in subtraction: -9,223,372,036,854,775,808 - 1
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test203()  throws Throwable  {
      long long0 = FastMath.decrementExact(9223372036854775766L);
      assertEquals(9223372036854775765L, long0);
  }

  @Test(timeout = 4000)
  public void test204()  throws Throwable  {
      try { 
        FastMath.decrementExact(Integer.MIN_VALUE);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in subtraction: -2,147,483,648 - 1
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test205()  throws Throwable  {
      int int0 = FastMath.decrementExact((-1156));
      assertEquals((-1157), int0);
  }

  @Test(timeout = 4000)
  public void test206()  throws Throwable  {
      try { 
        FastMath.incrementExact(9223372036854775807L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in addition: 9,223,372,036,854,775,807 + 1
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test207()  throws Throwable  {
      long long0 = FastMath.incrementExact(1023L);
      assertEquals(1024L, long0);
  }

  @Test(timeout = 4000)
  public void test208()  throws Throwable  {
      try { 
        FastMath.incrementExact(Integer.MAX_VALUE);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow in addition: 2,147,483,647 + 1
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test209()  throws Throwable  {
      int int0 = FastMath.incrementExact(104);
      assertEquals(105, int0);
  }

  @Test(timeout = 4000)
  public void test210()  throws Throwable  {
      try { 
        FastMath.toIntExact(9223372036854775787L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test211()  throws Throwable  {
      try { 
        FastMath.toIntExact((-9223372036854775808L));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // overflow
         //
         verifyException("org.apache.commons.math4.util.FastMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test212()  throws Throwable  {
      double double0 = FastMath.IEEEremainder(0.0F, 0.0F);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test213()  throws Throwable  {
      double double0 = FastMath.IEEEremainder(79.2366, Double.NEGATIVE_INFINITY);
      assertEquals(79.2366, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test214()  throws Throwable  {
      double double0 = FastMath.IEEEremainder(Double.NEGATIVE_INFINITY, Double.NEGATIVE_INFINITY);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test215()  throws Throwable  {
      double double0 = FastMath.hypot((-0.8282315591977749), Integer.MAX_VALUE);
      assertEquals(2.147483647E9, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test216()  throws Throwable  {
      double double0 = FastMath.hypot(9223372036854775801L, 84.73931296875567);
      assertEquals(9.223372036854776E18, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test217()  throws Throwable  {
      double double0 = FastMath.hypot(959.2110757876, Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test218()  throws Throwable  {
      double double0 = FastMath.hypot(Double.NaN, Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test219()  throws Throwable  {
      double double0 = FastMath.hypot((-1.0), Double.NEGATIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test220()  throws Throwable  {
      double double0 = FastMath.hypot(Float.NEGATIVE_INFINITY, Float.NEGATIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test221()  throws Throwable  {
      double double0 = FastMath.max((double) -0.0F, (double) -0.0F);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test222()  throws Throwable  {
      double double0 = FastMath.max(Double.NaN, (-709.782712893384));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test223()  throws Throwable  {
      double double0 = FastMath.max((double) 268435456L, (double) 268435456L);
      assertEquals(2.68435456E8, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test224()  throws Throwable  {
      double double0 = FastMath.max(709.782712893384, (-1757.3321));
      assertEquals(709.782712893384, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test225()  throws Throwable  {
      double double0 = FastMath.max((-1023.0), (-9.909612209943178E-8));
      assertEquals((-9.909612209943178E-8), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test226()  throws Throwable  {
      float float0 = FastMath.max(-0.0F, -0.0F);
      assertEquals(-0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test227()  throws Throwable  {
      float float0 = FastMath.max(Float.NaN, Float.NaN);
      assertEquals(Float.NaN, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test228()  throws Throwable  {
      float float0 = FastMath.max((float) 9223372036854775807L, (float) 9223372036854775807L);
      assertEquals(9.223372E18F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test229()  throws Throwable  {
      float float0 = FastMath.max((-3.4028235E38F), -0.0F);
      assertEquals(-0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test230()  throws Throwable  {
      long long0 = FastMath.max((-1242L), (-1242L));
      assertEquals((-1242L), long0);
  }

  @Test(timeout = 4000)
  public void test231()  throws Throwable  {
      long long0 = FastMath.max((long) 1500, (long) 128);
      assertEquals(1500L, long0);
  }

  @Test(timeout = 4000)
  public void test232()  throws Throwable  {
      int int0 = FastMath.max(3503, 3503);
      assertEquals(3503, int0);
  }

  @Test(timeout = 4000)
  public void test233()  throws Throwable  {
      int int0 = FastMath.max(1023, 7);
      assertEquals(1023, int0);
  }

  @Test(timeout = 4000)
  public void test234()  throws Throwable  {
      double double0 = FastMath.min(0.44691193103790283, 0.44691193103790283);
      assertEquals(0.44691193103790283, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test235()  throws Throwable  {
      double double0 = FastMath.min(Double.NaN, (double) 1492.7395F);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test236()  throws Throwable  {
      double double0 = FastMath.min((-3107.0934004886), Double.POSITIVE_INFINITY);
      assertEquals((-3107.0934004886), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test237()  throws Throwable  {
      double double0 = FastMath.min(76.278000720111, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test238()  throws Throwable  {
      double double0 = FastMath.min(-0.0, -0.0);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test239()  throws Throwable  {
      float float0 = FastMath.min(-0.0F, -0.0F);
      assertEquals(-0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test240()  throws Throwable  {
      float float0 = FastMath.min((-2617.79F), Float.NaN);
      assertEquals(Float.NaN, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test241()  throws Throwable  {
      float float0 = FastMath.min(35.0F, 67.0F);
      assertEquals(35.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test242()  throws Throwable  {
      float float0 = FastMath.min(56.989F, (-1807.9F));
      assertEquals((-1807.9F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test243()  throws Throwable  {
      float float0 = FastMath.min((-1.4E-45F), (-1.4E-45F));
      assertEquals((-1.4E-45F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test244()  throws Throwable  {
      long long0 = FastMath.min(131071L, 2438L);
      assertEquals(2438L, long0);
  }

  @Test(timeout = 4000)
  public void test245()  throws Throwable  {
      int int0 = FastMath.min((-28), 4);
      assertEquals((-28), int0);
  }

  @Test(timeout = 4000)
  public void test246()  throws Throwable  {
      int int0 = FastMath.min(2120, 867);
      assertEquals(867, int0);
  }

  @Test(timeout = 4000)
  public void test247()  throws Throwable  {
      double double0 = FastMath.rint(Double.POSITIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test248()  throws Throwable  {
      double double0 = FastMath.ceil(0.32341301441192627);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test249()  throws Throwable  {
      double double0 = FastMath.ceil(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test250()  throws Throwable  {
      double double0 = FastMath.ceil((-0.2499999701976776));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test251()  throws Throwable  {
      double double0 = FastMath.floor((-919.0));
      assertEquals((-919.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test252()  throws Throwable  {
      double double0 = FastMath.IEEEremainder(2.392500593858068E-17, (-0.2499999701976776));
      assertEquals(2.392500593858068E-17, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test253()  throws Throwable  {
      double double0 = FastMath.IEEEremainder((-370.1), 4.9E-324);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test254()  throws Throwable  {
      float float0 = FastMath.nextUp(1492.7395F);
      assertEquals(1492.7396F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test255()  throws Throwable  {
      float float0 = FastMath.nextDown(1376.6189F);
      assertEquals(1376.6188F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test256()  throws Throwable  {
      float float0 = FastMath.nextUp(Float.NEGATIVE_INFINITY);
      assertEquals((-3.4028235E38F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test257()  throws Throwable  {
      float float0 = FastMath.nextDown(Float.NEGATIVE_INFINITY);
      assertEquals(Float.NEGATIVE_INFINITY, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test258()  throws Throwable  {
      float float0 = FastMath.nextAfter(Float.NEGATIVE_INFINITY, Double.NaN);
      assertEquals(Float.NaN, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test259()  throws Throwable  {
      double double0 = FastMath.nextDown(427.31010576);
      assertEquals(427.31010575999994, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test260()  throws Throwable  {
      double double0 = FastMath.nextUp((double) 0.0F);
      assertEquals(4.9E-324, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test261()  throws Throwable  {
      double double0 = FastMath.nextDown((double) 0.0F);
      assertEquals((-4.9E-324), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test262()  throws Throwable  {
      double double0 = FastMath.nextAfter(Double.NEGATIVE_INFINITY, (double) 0L);
      assertEquals((-1.7976931348623157E308), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test263()  throws Throwable  {
      double double0 = FastMath.nextAfter(9.286532888251822E105, (double) Float.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test264()  throws Throwable  {
      double double0 = FastMath.nextAfter(Double.NaN, Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test265()  throws Throwable  {
      float float0 = FastMath.scalb((float) 225, 225);
      assertEquals(Float.POSITIVE_INFINITY, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test266()  throws Throwable  {
      float float0 = FastMath.scalb(1.1920929E-7F, 128);
      assertEquals(4.056482E31F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test267()  throws Throwable  {
      float float0 = FastMath.scalb(1.4E-45F, 276);
      assertEquals(1.7014118E38F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test268()  throws Throwable  {
      float float0 = FastMath.scalb((float) (-168), (-168));
      assertEquals(-0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test269()  throws Throwable  {
      float float0 = FastMath.scalb((float) (-138), (-138));
      assertEquals((-3.9604E-40F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test270()  throws Throwable  {
      float float0 = FastMath.scalb(13.0F, 3599);
      assertEquals(Float.POSITIVE_INFINITY, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test271()  throws Throwable  {
      float float0 = FastMath.scalb((-5.68165F), 144);
      assertEquals(Float.NEGATIVE_INFINITY, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test272()  throws Throwable  {
      float float0 = FastMath.scalb(1.1920929E-7F, (-1347));
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test273()  throws Throwable  {
      float float0 = FastMath.scalb(0.0F, (-2147483646));
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test274()  throws Throwable  {
      float float0 = FastMath.scalb(Float.POSITIVE_INFINITY, 1278);
      assertEquals(Float.POSITIVE_INFINITY, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test275()  throws Throwable  {
      float float0 = FastMath.scalb(Float.NaN, (-662));
      assertEquals(Float.NaN, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test276()  throws Throwable  {
      float float0 = FastMath.scalb(0.0F, 0);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test277()  throws Throwable  {
      float float0 = FastMath.scalb((-0.18688977F), 2049870754);
      assertEquals(Float.NEGATIVE_INFINITY, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test278()  throws Throwable  {
      float float0 = FastMath.scalb((-1156.86F), (-1790));
      assertEquals(-0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test279()  throws Throwable  {
      double double0 = FastMath.scalb(3.293665086980829E-131, 1111);
      assertEquals(9.16230234691047E203, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test280()  throws Throwable  {
      double double0 = FastMath.scalb(1.1932800507380155, (-1023));
      assertEquals(1.327568123387653E-308, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test281()  throws Throwable  {
      double double0 = FastMath.scalb(0.4794255495071411, (-1035));
      assertEquals(1.302193917613E-312, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test282()  throws Throwable  {
      double double0 = FastMath.scalb((double) (-1023), (-1023));
      assertEquals((-1.1381252786264335E-305), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test283()  throws Throwable  {
      double double0 = FastMath.scalb((double) (-9223372036854775808L), (-2058));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test284()  throws Throwable  {
      double double0 = FastMath.scalb((double) 1137, 2135327837);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test285()  throws Throwable  {
      double double0 = FastMath.scalb((-89.5), 346944);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test286()  throws Throwable  {
      double double0 = FastMath.scalb(131.892745253076, (-2146595674));
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test287()  throws Throwable  {
      double double0 = FastMath.scalb((double) (-4155), (-4155));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test288()  throws Throwable  {
      double double0 = FastMath.scalb(Double.POSITIVE_INFINITY, 2183);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test289()  throws Throwable  {
      double double0 = FastMath.scalb(Double.NaN, (-1275));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test290()  throws Throwable  {
      double double0 = FastMath.scalb((-2.2153227096187463E-9), 1500);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test291()  throws Throwable  {
      double double0 = FastMath.hypot(0.0F, 0.0F);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test292()  throws Throwable  {
      float float0 = FastMath.ulp(Float.NEGATIVE_INFINITY);
      assertEquals(Float.POSITIVE_INFINITY, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test293()  throws Throwable  {
      double double0 = FastMath.ulp(Double.NEGATIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test294()  throws Throwable  {
      double double0 = FastMath.ulp((-1335.066));
      assertEquals(2.2737367544323206E-13, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test295()  throws Throwable  {
      double double0 = FastMath.toDegrees(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test296()  throws Throwable  {
      double double0 = FastMath.toDegrees(1851.6);
      assertEquals(106088.86534642322, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test297()  throws Throwable  {
      double double0 = FastMath.toDegrees(Double.POSITIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test298()  throws Throwable  {
      double double0 = FastMath.toRadians((-4.9E-324));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test299()  throws Throwable  {
      double double0 = FastMath.toRadians(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test300()  throws Throwable  {
      double double0 = FastMath.toRadians(2096.1290614);
      assertEquals(36.58435366816838, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test301()  throws Throwable  {
      double double0 = FastMath.toRadians(Double.NEGATIVE_INFINITY);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test302()  throws Throwable  {
      double double0 = FastMath.cbrt(Double.POSITIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test303()  throws Throwable  {
      double double0 = FastMath.cbrt(1.00605438061E-312);
      assertEquals(1.0020140676778003E-104, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test304()  throws Throwable  {
      double double0 = FastMath.cbrt(0.0F);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test305()  throws Throwable  {
      double double0 = FastMath.cbrt((-1664.48521698825));
      assertEquals((-11.851135967318369), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test306()  throws Throwable  {
      double double0 = FastMath.acos(4.546040329134E-311);
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test307()  throws Throwable  {
      double double0 = FastMath.acos(0.0F);
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test308()  throws Throwable  {
      double double0 = FastMath.acos(1.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test309()  throws Throwable  {
      double double0 = FastMath.acos((-1.0));
      assertEquals(3.141592653589793, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test310()  throws Throwable  {
      double double0 = FastMath.acos((-129));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test311()  throws Throwable  {
      double double0 = FastMath.acos(1064.099577294);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test312()  throws Throwable  {
      double double0 = FastMath.acos(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test313()  throws Throwable  {
      double double0 = FastMath.asin(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test314()  throws Throwable  {
      double double0 = FastMath.asin((-1L));
      assertEquals((-1.5707963267948966), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test315()  throws Throwable  {
      double double0 = FastMath.asin(1.0);
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test316()  throws Throwable  {
      double double0 = FastMath.asin((-2040109414));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test317()  throws Throwable  {
      double double0 = FastMath.asin(3487.67574499604);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test318()  throws Throwable  {
      double double0 = FastMath.asin(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test319()  throws Throwable  {
      double double0 = FastMath.atan2(1.0908029079437256, 4.9E-324);
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test320()  throws Throwable  {
      double double0 = FastMath.atan2(180L, (-2.2250738585072014E-308));
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test321()  throws Throwable  {
      double double0 = FastMath.atan2(4817L, 0L);
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test322()  throws Throwable  {
      double double0 = FastMath.atan2((-2644281811660520851L), 0L);
      assertEquals((-1.5707963267948966), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test323()  throws Throwable  {
      double double0 = FastMath.atan2(2.718281828459045, Double.NEGATIVE_INFINITY);
      assertEquals(3.141592653589793, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test324()  throws Throwable  {
      double double0 = FastMath.atan2((-0.2499999701976776), Double.NEGATIVE_INFINITY);
      assertEquals((-3.141592653589793), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test325()  throws Throwable  {
      double double0 = FastMath.atan2(4.503599627370496E15, Double.POSITIVE_INFINITY);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test326()  throws Throwable  {
      double double0 = FastMath.atan2((-2377.45), Double.POSITIVE_INFINITY);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test327()  throws Throwable  {
      double double0 = FastMath.atan2(Double.NEGATIVE_INFINITY, -0.0);
      assertEquals((-1.5707963267948966), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test328()  throws Throwable  {
      double double0 = FastMath.atan2(Double.NEGATIVE_INFINITY, Double.POSITIVE_INFINITY);
      assertEquals((-0.7853981633974483), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test329()  throws Throwable  {
      double double0 = FastMath.atan2(Double.NEGATIVE_INFINITY, Double.NEGATIVE_INFINITY);
      assertEquals((-2.356194490192345), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test330()  throws Throwable  {
      double double0 = FastMath.atan2(Double.POSITIVE_INFINITY, Double.POSITIVE_INFINITY);
      assertEquals(0.7853981633974483, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test331()  throws Throwable  {
      double double0 = FastMath.atan2(Double.POSITIVE_INFINITY, (-1560.0));
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test332()  throws Throwable  {
      double double0 = FastMath.atan2(0.0F, 0.0F);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test333()  throws Throwable  {
      double double0 = FastMath.atan2(0L, (-2644281811660520851L));
      assertEquals(3.141592653589793, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test334()  throws Throwable  {
      double double0 = FastMath.atan2(0.0, Float.NEGATIVE_INFINITY);
      assertEquals(3.141592653589793, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test335()  throws Throwable  {
      double double0 = FastMath.atan2(0.0, Double.POSITIVE_INFINITY);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test336()  throws Throwable  {
      double double0 = FastMath.atan2(-0.0, -0.0);
      assertEquals((-3.141592653589793), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test337()  throws Throwable  {
      double double0 = FastMath.atan2(Double.NaN, 0.5);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test338()  throws Throwable  {
      double double0 = FastMath.atan2(Double.NaN, Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test339()  throws Throwable  {
      double double0 = FastMath.atan2((-1069.1148667571), (-1069.1148667571));
      assertEquals((-2.356194490192345), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test340()  throws Throwable  {
      double double0 = FastMath.asin((-1.0E-6));
      assertEquals((-1.0000000000001666E-6), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test341()  throws Throwable  {
      double double0 = FastMath.atan(Double.NEGATIVE_INFINITY);
      assertEquals((-1.5707963267948966), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test342()  throws Throwable  {
      double double0 = FastMath.atan2(5.04E-322, (-4807.105335815362));
      assertEquals(3.141592653589793, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test343()  throws Throwable  {
      double double0 = FastMath.tan(Double.POSITIVE_INFINITY);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test344()  throws Throwable  {
      double double0 = FastMath.tan(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test345()  throws Throwable  {
      double double0 = FastMath.tan(0.0F);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test346()  throws Throwable  {
      double double0 = FastMath.tan(-0.0);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test347()  throws Throwable  {
      double double0 = FastMath.cos(Double.NEGATIVE_INFINITY);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test348()  throws Throwable  {
      double double0 = FastMath.cos(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test349()  throws Throwable  {
      double double0 = FastMath.sin(1.2897084285532175E95);
      assertEquals(0.9923238158869476, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test350()  throws Throwable  {
      double double0 = FastMath.sin(Double.NEGATIVE_INFINITY);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test351()  throws Throwable  {
      double double0 = FastMath.sin(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test352()  throws Throwable  {
      double double0 = FastMath.sin(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test353()  throws Throwable  {
      double double0 = FastMath.sin(-0.0F);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test354()  throws Throwable  {
      double double0 = FastMath.tan(4.730212475795673E288);
      assertEquals((-0.5444046952004127), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test355()  throws Throwable  {
      double double0 = FastMath.cos(1.21645100408832E17);
      assertEquals(0.9997869718755525, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test356()  throws Throwable  {
      double double0 = FastMath.tan((-2.147483619E9));
      assertEquals((-1.8950714855924962), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test357()  throws Throwable  {
      double double0 = FastMath.sin(1.633123935319536E16);
      assertEquals(0.6496791463811216, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test358()  throws Throwable  {
      double double0 = FastMath.tan(1.2247224482958058E115);
      assertEquals(0.5540651528228772, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test359()  throws Throwable  {
      double double0 = FastMath.cos(4577762542105553359L);
      assertEquals((-0.9977390214769539), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test360()  throws Throwable  {
      double double0 = FastMath.sin((-4.281623811241125E59));
      assertEquals((-0.44722237502191087), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test361()  throws Throwable  {
      double double0 = FastMath.cos((-1.8908603201210102E262));
      assertEquals((-0.010181165796261842), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test362()  throws Throwable  {
      double double0 = FastMath.tan((-9223372036854775808L));
      assertEquals((-84.73931296875567), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test363()  throws Throwable  {
      double double0 = FastMath.tan((-7.877917738262007E-9));
      assertEquals((-7.877917738262007E-9), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test364()  throws Throwable  {
      double double0 = FastMath.tan((-2644281811660520851L));
      assertEquals((-2.489134598855274), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test365()  throws Throwable  {
      double double0 = FastMath.sin((-7.877917738262007E-9));
      assertEquals((-7.877917738262007E-9), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test366()  throws Throwable  {
      double double0 = FastMath.pow(Double.NaN, (-1531L));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test367()  throws Throwable  {
      double double0 = FastMath.pow(0.0, (-2045222521));
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test368()  throws Throwable  {
      double double0 = FastMath.pow(0.0030356132194930383, 347);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test369()  throws Throwable  {
      double double0 = FastMath.pow((-648.4416), (-925L));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test370()  throws Throwable  {
      double double0 = FastMath.pow(Double.POSITIVE_INFINITY, 1.1427077073965515E-17);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test371()  throws Throwable  {
      double double0 = FastMath.pow(Double.NaN, 2.718281828459045);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test372()  throws Throwable  {
      double double0 = FastMath.pow(Double.POSITIVE_INFINITY, (-2.2250738585072014E-308));
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test373()  throws Throwable  {
      double double0 = FastMath.pow(0.0, 3.141592653589793);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test374()  throws Throwable  {
      double double0 = FastMath.pow(0.0, (-1.4303708525293404));
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test375()  throws Throwable  {
      double double0 = FastMath.pow((double) 1L, (double) (-1L));
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test376()  throws Throwable  {
      double double0 = FastMath.pow(7.580392204597681E-144, (-2.644281811660521E18));
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test377()  throws Throwable  {
      double double0 = FastMath.pow((-1228.7872), (-1228.7872));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test378()  throws Throwable  {
      double double0 = FastMath.pow((-1.0), (double) (-9223372036854775808L));
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test379()  throws Throwable  {
      double double0 = FastMath.pow(1.0, Double.POSITIVE_INFINITY);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test380()  throws Throwable  {
      double double0 = FastMath.pow((-1.5707963267948966), Double.NEGATIVE_INFINITY);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test381()  throws Throwable  {
      double double0 = FastMath.pow(Double.POSITIVE_INFINITY, Double.POSITIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test382()  throws Throwable  {
      double double0 = FastMath.pow(Double.NaN, (-1.7976931348623157E308));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test383()  throws Throwable  {
      double double0 = FastMath.pow(3.076063086193525E-48, Double.NEGATIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test384()  throws Throwable  {
      double double0 = FastMath.pow(Double.NaN, Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test385()  throws Throwable  {
      double double0 = FastMath.pow((double) 0.0F, (double) 0.0F);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test386()  throws Throwable  {
      double double0 = FastMath.log10(1.883511811213715E-8);
      assertEquals((-7.725031652058082), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test387()  throws Throwable  {
      double double0 = FastMath.log1p(Double.POSITIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test388()  throws Throwable  {
      double double0 = FastMath.log1p((-1.0));
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test389()  throws Throwable  {
      double double0 = FastMath.pow(1.0, 0.9808930158615112);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test390()  throws Throwable  {
      double double0 = FastMath.log((double) 1);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test391()  throws Throwable  {
      double double0 = FastMath.log1p(0.4518963694572449);
      assertEquals(0.3728705429583664, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test392()  throws Throwable  {
      double double0 = FastMath.log1p((-0.3058015757857271));
      assertEquals((-0.36499744548748997), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test393()  throws Throwable  {
      double double0 = FastMath.pow(5.33839690397E-312, 5.33839690397E-312);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test394()  throws Throwable  {
      double double0 = FastMath.log10(Double.POSITIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test395()  throws Throwable  {
      double double0 = FastMath.asinh(Double.NEGATIVE_INFINITY);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test396()  throws Throwable  {
      double double0 = FastMath.log1p((-1541.8962270457966));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test397()  throws Throwable  {
      double double0 = FastMath.log(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test398()  throws Throwable  {
      double double0 = FastMath.expm1((-0.16666666666666666));
      assertEquals((-0.15351827510938593), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test399()  throws Throwable  {
      double double0 = FastMath.expm1(0L);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test400()  throws Throwable  {
      double double0 = FastMath.expm1(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test401()  throws Throwable  {
      double double0 = FastMath.pow(1.2246467991473532E-16, 1.2246467991473532E-16);
      assertEquals(0.9999999999999956, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test402()  throws Throwable  {
      double double0 = FastMath.expm1(982199710);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test403()  throws Throwable  {
      double double0 = FastMath.exp((-709.4632026663587));
      assertEquals(7.656776469938204E-309, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test404()  throws Throwable  {
      double double0 = FastMath.expm1((-1505.62989275757));
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test405()  throws Throwable  {
      double double0 = FastMath.exp(Double.NEGATIVE_INFINITY);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test406()  throws Throwable  {
      float float0 = FastMath.signum(0.15918939F);
      assertEquals(1.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test407()  throws Throwable  {
      float float0 = FastMath.signum((-75.275F));
      assertEquals((-1.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test408()  throws Throwable  {
      float float0 = FastMath.signum(0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test409()  throws Throwable  {
      double double0 = FastMath.signum(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test410()  throws Throwable  {
      double double0 = FastMath.signum(Double.NEGATIVE_INFINITY);
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test411()  throws Throwable  {
      double double0 = FastMath.signum(661.6526847853121);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test412()  throws Throwable  {
      double double0 = FastMath.atanh(0.031);
      assertEquals(0.031009936063096846, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test413()  throws Throwable  {
      double double0 = FastMath.atanh(0.035367143837291316);
      assertEquals(0.03538190106636413, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test414()  throws Throwable  {
      double double0 = FastMath.asinh(0.031);
      assertEquals(0.03099503697929222, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test415()  throws Throwable  {
      double double0 = FastMath.asinh((-0.03641835F));
      assertEquals((-0.0364103030993221), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test416()  throws Throwable  {
      double double0 = FastMath.asinh(-0.0);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test417()  throws Throwable  {
      double double0 = FastMath.tanh((-0.2499999701976776));
      assertEquals((-0.24491863438908335), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test418()  throws Throwable  {
      double double0 = FastMath.tanh(-0.0F);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test419()  throws Throwable  {
      double double0 = FastMath.tanh(2286.9788592114064);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test420()  throws Throwable  {
      double double0 = FastMath.tanh(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test421()  throws Throwable  {
      double double0 = FastMath.tanh((-1357.0));
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test422()  throws Throwable  {
      double double0 = FastMath.sinh((-20.0));
      assertEquals((-2.4258259770489514E8), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test423()  throws Throwable  {
      double double0 = FastMath.sinh(0.0011432235873651375);
      assertEquals(0.0011432238363897696, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test424()  throws Throwable  {
      double double0 = FastMath.sinh(0.0F);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test425()  throws Throwable  {
      double double0 = FastMath.sinh((-919.0));
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test426()  throws Throwable  {
      double double0 = FastMath.sinh((-425.12474935763714));
      assertEquals((-2.129623207472439E184), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test427()  throws Throwable  {
      double double0 = FastMath.sinh(128);
      assertEquals(1.9438542029972974E55, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test428()  throws Throwable  {
      double double0 = FastMath.sinh(1.8176095E7);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test429()  throws Throwable  {
      double double0 = FastMath.sinh(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test430()  throws Throwable  {
      double double0 = FastMath.cosh((-563.14));
      assertEquals(1.8516740631072975E244, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test431()  throws Throwable  {
      double double0 = FastMath.cosh(434.69094305257);
      assertEquals(3.039820261396126E188, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test432()  throws Throwable  {
      double double0 = FastMath.cosh(3136.66);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test433()  throws Throwable  {
      double double0 = FastMath.cosh(Double.NaN);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test434()  throws Throwable  {
      long long0 = FastMath.round(Double.POSITIVE_INFINITY);
      assertEquals(9223372036854775807L, long0);
  }

  @Test(timeout = 4000)
  public void test435()  throws Throwable  {
      int int0 = FastMath.round(-0.0F);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test436()  throws Throwable  {
      double double0 = FastMath.cosh((-3107.0934004886));
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test437()  throws Throwable  {
      double double0 = FastMath.random();
      double double1 = FastMath.random();
      assertNotEquals(double1, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test438()  throws Throwable  {
      FastMath.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test439()  throws Throwable  {
      double double0 = FastMath.nextUp((-1277.9198922036092));
      assertEquals((-1277.919892203609), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test440()  throws Throwable  {
      double double0 = FastMath.acos((-2.0332050860436034E-263));
      assertEquals(1.5707963267948966, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test441()  throws Throwable  {
      int int0 = FastMath.getExponent(0.0F);
      assertEquals((-127), int0);
  }

  @Test(timeout = 4000)
  public void test442()  throws Throwable  {
      long long0 = FastMath.abs((-1L));
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test443()  throws Throwable  {
      double double0 = FastMath.cos((-734.5852280938));
      assertEquals(0.8538531197903286, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test444()  throws Throwable  {
      double double0 = FastMath.pow((-1750.88), 2475);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

@Test
  public void test047_pred1()  throws Throwable  {
      double double0 = FastMath.exp((-746.0));
      assertEquals(0.0, double0, 0.01);
}

@Test
  public void test403_pred2()  throws Throwable  {
      double double0 = FastMath.exp((-709.4632026663587));
      assertEquals(7.656776469938204E-309, double0, 0.01);
}

@Test
  public void test405_pred3()  throws Throwable  {
      double double0 = FastMath.exp(Double.NEGATIVE_INFINITY);
      assertEquals(0.0, double0, 0.01);
}
}