/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 16 10:36:20 GMT 2025
 */

package org.apache.commons.math4.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.stat.descriptive.moment.StandardDeviation;
import org.apache.commons.math4.stat.descriptive.summary.SumOfLogs;
import org.apache.commons.math4.stat.descriptive.summary.SumOfSquares;
import org.apache.commons.math4.util.MathArrays;
import org.apache.commons.math4.util.ResizableDoubleArray;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ResizableDoubleArray_ESTest extends ResizableDoubleArray_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      double[] doubleArray0 = new double[5];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(resizableDoubleArray0);
      assertTrue(resizableDoubleArray1.equals((Object)resizableDoubleArray0));
      
      resizableDoubleArray1.addElementRolling(2.0);
      resizableDoubleArray0.equals(resizableDoubleArray1);
      assertEquals(2.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      double[] doubleArray0 = new double[3];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray();
      boolean boolean0 = resizableDoubleArray1.equals(resizableDoubleArray0);
      assertEquals(2.5, resizableDoubleArray1.getContractionCriterion(), 0.01);
      assertEquals(16, resizableDoubleArray1.getCapacity());
      assertEquals(3, resizableDoubleArray0.getNumElements());
      assertEquals(4, resizableDoubleArray0.getCapacity());
      assertFalse(boolean0);
      assertEquals(2.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[1];
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(825, 1.8500902652740479, 2.5, resizableDoubleArray_ExpansionMode0, doubleArray0);
      boolean boolean0 = resizableDoubleArray0.equals(resizableDoubleArray1);
      assertEquals(1.8500902652740479, resizableDoubleArray1.getExpansionFactor(), 0.01);
      assertEquals(2.5, resizableDoubleArray1.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray1.getNumElements());
      assertEquals(825, resizableDoubleArray1.getCapacity());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(3026, 3026, 4.503599627370496E15);
      boolean boolean0 = resizableDoubleArray1.equals(resizableDoubleArray0);
      assertEquals(3026.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
      assertFalse(boolean0);
      assertEquals(0, resizableDoubleArray1.getNumElements());
      assertEquals(4.503599627370496E15, resizableDoubleArray1.getContractionCriterion(), 0.01);
      assertEquals(3026, resizableDoubleArray1.getCapacity());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38, 38, 3475.506, resizableDoubleArray_ExpansionMode0, doubleArray0);
      double double0 = resizableDoubleArray0.addElementRolling(38);
      assertEquals(38, resizableDoubleArray0.getCapacity());
      assertEquals(0.0, double0, 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(3475.506, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(38.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[1];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38, 38, 38, resizableDoubleArray_ExpansionMode0, doubleArray0);
      resizableDoubleArray0.addElementRolling(38);
      resizableDoubleArray0.setNumElements(38);
      assertEquals(38, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      resizableDoubleArray0.setNumElements(2);
      resizableDoubleArray0.addElementRolling(0);
      resizableDoubleArray0.setNumElements(0);
      assertEquals(0, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setElement(1193, 1193);
      resizableDoubleArray0.setElement(1193, 1193);
      assertEquals(1194, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      assertEquals(0, resizableDoubleArray0.getNumElements());
      
      resizableDoubleArray0.setElement(0, 0);
      assertEquals(1, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      double[] doubleArray0 = new double[3];
      resizableDoubleArray0.addElements(doubleArray0);
      resizableDoubleArray0.getElement(0);
      assertEquals(4, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.MULTIPLICATIVE;
      double[] doubleArray0 = new double[7];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(16, 16, 16, resizableDoubleArray_ExpansionMode0, doubleArray0);
      // Undeclared exception!
      try { 
        resizableDoubleArray0.getElement(16);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      resizableDoubleArray0.setNumElements(2830);
      resizableDoubleArray0.discardFrontElements(5);
      assertEquals(2825, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(1422, (-1445.726213460133));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // -1,445.226 is smaller than, or equal to, the minimum (1): contraction criteria smaller than one (-1,445.226).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria.
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.checkContractExpand(100.0, 100.0);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      double double0 = resizableDoubleArray0.substituteMostRecentElement(68);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(2, resizableDoubleArray0.getNumElements());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(3, resizableDoubleArray0.getCapacity());
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2432);
      resizableDoubleArray0.setElement(2432, (-303.16158));
      double double0 = resizableDoubleArray0.substituteMostRecentElement(3416.24336784);
      assertEquals(2433, resizableDoubleArray0.getNumElements());
      assertEquals((-303.16158), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      resizableDoubleArray0.setNumElements(2);
      resizableDoubleArray0.addElementRolling(2);
      int int0 = resizableDoubleArray0.getStartIndex();
      assertEquals(2, resizableDoubleArray0.getNumElements());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(3938);
      int int0 = resizableDoubleArray0.getNumElements();
      assertEquals(3938, resizableDoubleArray0.getCapacity());
      assertEquals(3938, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      resizableDoubleArray0.setNumElements(2);
      resizableDoubleArray0.getElements();
      assertEquals(2, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(274);
      resizableDoubleArray0.getElement(6);
      assertEquals(274, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(2080);
      resizableDoubleArray0.addElement(2080);
      double double0 = resizableDoubleArray0.getElement(2080);
      assertEquals(2081, resizableDoubleArray0.getNumElements());
      assertEquals(2080.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[3];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(57, 57, 57, resizableDoubleArray_ExpansionMode0, doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = resizableDoubleArray0.copy();
      assertEquals(4, resizableDoubleArray1.getCapacity());
      assertEquals(57.0, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(3, resizableDoubleArray1.getNumElements());
      assertTrue(resizableDoubleArray1.equals((Object)resizableDoubleArray0));
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(3938);
      resizableDoubleArray0.addElement(3938);
      StandardDeviation standardDeviation0 = new StandardDeviation();
      double double0 = resizableDoubleArray0.compute(standardDeviation0);
      assertEquals(3939, resizableDoubleArray0.getNumElements());
      assertEquals(62.74551979122924, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(401);
      SumOfLogs sumOfLogs0 = new SumOfLogs();
      resizableDoubleArray0.compute(sumOfLogs0);
      assertEquals(401, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      double[] doubleArray0 = new double[5];
      doubleArray0[0] = (double) 2;
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      double double0 = resizableDoubleArray0.addElementRolling(2.0);
      assertEquals(6, resizableDoubleArray0.getCapacity());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(5, resizableDoubleArray0.getNumElements());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(2.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      double[] doubleArray0 = new double[7];
      doubleArray0[0] = (-1.0);
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      double double0 = resizableDoubleArray0.addElementRolling((-158.0928));
      assertEquals((-1.0), double0, 0.01);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(8, resizableDoubleArray0.getCapacity());
      assertEquals(7, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.compute((MathArrays.Function) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      try { 
        resizableDoubleArray0.checkContractExpand((-3279.98181135), (-3279.98181135));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // -3,279.982 is smaller than, or equal to, the minimum (1): contraction criteria smaller than one (-3,279.982).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria.
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.addElements((double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray((ResizableDoubleArray) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.MULTIPLICATIVE;
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(857, (-2799.826555457084), 857, resizableDoubleArray_ExpansionMode0, doubleArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 857 is smaller than, or equal to, the minimum (1): expansion factor smaller than one (-2,799.827)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray((-1), (-1), (-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // initial capacity (-1) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(0, 0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // initial capacity (0) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray((-915));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // initial capacity (-915) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38, 38, 38, resizableDoubleArray_ExpansionMode0, doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = resizableDoubleArray0.copy();
      assertTrue(resizableDoubleArray1.equals((Object)resizableDoubleArray0));
      
      resizableDoubleArray1.addElementRolling(38);
      boolean boolean0 = resizableDoubleArray1.equals(resizableDoubleArray0);
      assertFalse(resizableDoubleArray1.equals((Object)resizableDoubleArray0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(doubleArray0);
      resizableDoubleArray1.setElement(3938, 3938);
      resizableDoubleArray1.equals(resizableDoubleArray0);
      assertEquals(3939, resizableDoubleArray1.getCapacity());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.MULTIPLICATIVE;
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(3938, 2.5, 2.5, resizableDoubleArray_ExpansionMode0, doubleArray0);
      boolean boolean0 = resizableDoubleArray0.equals(resizableDoubleArray1);
      assertFalse(boolean0);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(3938, resizableDoubleArray1.getCapacity());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray1.getNumElements());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(1894, 1894);
      boolean boolean0 = resizableDoubleArray0.equals(resizableDoubleArray1);
      assertEquals(1894.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
      assertEquals(0, resizableDoubleArray1.getNumElements());
      assertEquals(1894, resizableDoubleArray1.getCapacity());
      assertFalse(boolean0);
      assertEquals(1894.5, resizableDoubleArray1.getContractionCriterion(), 0.01);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      Object object0 = new Object();
      boolean boolean0 = resizableDoubleArray0.equals(object0);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertFalse(boolean0);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      boolean boolean0 = resizableDoubleArray0.equals(resizableDoubleArray0);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertTrue(boolean0);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(resizableDoubleArray0);
      boolean boolean0 = resizableDoubleArray1.equals(resizableDoubleArray0);
      assertEquals(16, resizableDoubleArray1.getCapacity());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(2.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[3];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(57, 57, 57, resizableDoubleArray_ExpansionMode0, doubleArray0);
      resizableDoubleArray0.expand();
      assertEquals(61, resizableDoubleArray0.getCapacity());
      
      resizableDoubleArray0.addElementRolling(57);
      assertEquals(4, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      try { 
        resizableDoubleArray0.setNumElements((-2392));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // index (-2,392) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.setElement((-28), (-28));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.getElement((-1852));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.getElement(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(328);
      resizableDoubleArray0.discardMostRecentElements(4);
      assertEquals(324, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      try { 
        resizableDoubleArray0.discardFrontElements((-504));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // cannot discard a negative number of elements (-504)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(1, 1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 1.5 is smaller than, or equal to, the minimum (1): expansion factor smaller than one (1)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(1, 1, 1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 1 is smaller than, or equal to, the minimum (1): contraction criteria smaller than one (1).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria.
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(16, 16, (-1826.841634));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // -1,826.842 is smaller than the minimum (1): contraction criteria (-1,826.842) smaller than the expansion factor (16).  This would lead to a never ending loop of expansion and contraction as a newly expanded internal storage array would immediately satisfy the criteria for contraction.
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      try { 
        resizableDoubleArray0.substituteMostRecentElement(2.5);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // cannot substitute an element from an empty array
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.addElement(1337.497924321178);
      double double0 = resizableDoubleArray0.substituteMostRecentElement(1337.497924321178);
      assertEquals(1, resizableDoubleArray0.getNumElements());
      assertEquals(1337.497924321178, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38);
      double double0 = resizableDoubleArray0.addElementRolling(38);
      assertEquals(1, resizableDoubleArray0.getCapacity());
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(870);
      resizableDoubleArray0.setNumElements(870);
      resizableDoubleArray0.addElement((-196.83991928171));
      double double0 = resizableDoubleArray0.getElement(870);
      assertEquals(871, resizableDoubleArray0.getNumElements());
      assertEquals((-196.83991928171), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.MULTIPLICATIVE;
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray((-1421), (-1421), (-1421), resizableDoubleArray_ExpansionMode0, doubleArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // initial capacity (-1,421) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray((double[]) null);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[3];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(57, 57, 57, resizableDoubleArray_ExpansionMode0, doubleArray0);
      resizableDoubleArray0.hashCode();
      assertEquals(57.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(3, resizableDoubleArray0.getNumElements());
      assertEquals(4, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      double[] doubleArray0 = new double[10];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      // Undeclared exception!
      try { 
        resizableDoubleArray0.setElement(Integer.MAX_VALUE, Integer.MAX_VALUE);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      int int0 = resizableDoubleArray0.getNumElements();
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38);
      int int0 = resizableDoubleArray0.getCapacity();
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(38, int0);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.discardFrontElements(0);
      assertEquals(1, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      double[] doubleArray0 = resizableDoubleArray0.getElements();
      assertEquals(0, doubleArray0.length);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(2.0, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(2, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      
      resizableDoubleArray0.contract();
      assertEquals(1, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      int int0 = resizableDoubleArray0.getStartIndex();
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2, resizableDoubleArray0.getCapacity());
      assertEquals(2.0, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, int0);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38);
      resizableDoubleArray0.getExpansionMode();
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(38, resizableDoubleArray0.getCapacity());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38);
      SumOfSquares sumOfSquares0 = new SumOfSquares();
      resizableDoubleArray0.compute(sumOfSquares0);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(38, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      double[] doubleArray0 = resizableDoubleArray0.getArrayRef();
      assertEquals(16, doubleArray0.length);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      try { 
        resizableDoubleArray0.discardMostRecentElements(3936);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // cannot discard 3,936 elements from a 0 elements array
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      double double0 = resizableDoubleArray0.getExpansionFactor();
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, double0, 0.01);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      double double0 = resizableDoubleArray0.getContractionCriterion();
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(2.0, double0, 0.01);
      assertEquals(2, resizableDoubleArray0.getCapacity());
      assertEquals(0, resizableDoubleArray0.getNumElements());
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      resizableDoubleArray0.clear();
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertEquals(0, resizableDoubleArray0.getNumElements());
  }

@Test
  public void test00_pred1()  throws Throwable  {
      double[] doubleArray0 = new double[5];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(resizableDoubleArray0);
      assertTrue(resizableDoubleArray1.equals((Object)resizableDoubleArray0));
      
      resizableDoubleArray1.addElementRolling(2.0);
      resizableDoubleArray0.equals(resizableDoubleArray1);
      assertEquals(2.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
}

@Test
  public void test01_pred2()  throws Throwable  {
      double[] doubleArray0 = new double[3];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray();
      boolean boolean0 = resizableDoubleArray1.equals(resizableDoubleArray0);
      assertEquals(2.5, resizableDoubleArray1.getContractionCriterion(), 0.01);
      assertEquals(16, resizableDoubleArray1.getCapacity());
      assertEquals(3, resizableDoubleArray0.getNumElements());
      assertEquals(4, resizableDoubleArray0.getCapacity());
      assertFalse(boolean0);
      assertEquals(2.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
}

@Test
  public void test02_pred3()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[1];
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(825, 1.8500902652740479, 2.5, resizableDoubleArray_ExpansionMode0, doubleArray0);
      boolean boolean0 = resizableDoubleArray0.equals(resizableDoubleArray1);
      assertEquals(1.8500902652740479, resizableDoubleArray1.getExpansionFactor(), 0.01);
      assertEquals(2.5, resizableDoubleArray1.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray1.getNumElements());
      assertEquals(825, resizableDoubleArray1.getCapacity());
      assertFalse(boolean0);
}

@Test
  public void test03_pred4()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(3026, 3026, 4.503599627370496E15);
      boolean boolean0 = resizableDoubleArray1.equals(resizableDoubleArray0);
      assertEquals(3026.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
      assertFalse(boolean0);
      assertEquals(0, resizableDoubleArray1.getNumElements());
      assertEquals(4.503599627370496E15, resizableDoubleArray1.getContractionCriterion(), 0.01);
      assertEquals(3026, resizableDoubleArray1.getCapacity());
}

@Test
  public void test04_pred5()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38, 38, 3475.506, resizableDoubleArray_ExpansionMode0, doubleArray0);
      double double0 = resizableDoubleArray0.addElementRolling(38);
      assertEquals(38, resizableDoubleArray0.getCapacity());
      assertEquals(0.0, double0, 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(3475.506, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(38.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test05_pred6()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[1];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38, 38, 38, resizableDoubleArray_ExpansionMode0, doubleArray0);
      resizableDoubleArray0.addElementRolling(38);
      resizableDoubleArray0.setNumElements(38);
      assertEquals(38, resizableDoubleArray0.getNumElements());
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getNumElements());

}

@Test
  public void test06_pred7()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      resizableDoubleArray0.setNumElements(2);
      resizableDoubleArray0.addElementRolling(0);
      resizableDoubleArray0.setNumElements(0);
      assertEquals(0, resizableDoubleArray0.getNumElements());
    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getNumElements());

}

@Test
  public void test07_pred8()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setElement(1193, 1193);
      resizableDoubleArray0.setElement(1193, 1193);
      assertEquals(1194, resizableDoubleArray0.getCapacity());
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test08_pred9()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      assertEquals(0, resizableDoubleArray0.getNumElements());
      
      resizableDoubleArray0.setElement(0, 0);
      assertEquals(1, resizableDoubleArray0.getNumElements());
}

@Test
  public void test09_pred10()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      double[] doubleArray0 = new double[3];
      resizableDoubleArray0.addElements(doubleArray0);
      resizableDoubleArray0.getElement(0);
      assertEquals(4, resizableDoubleArray0.getCapacity());
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test10_pred11()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.MULTIPLICATIVE;
      double[] doubleArray0 = new double[7];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(16, 16, 16, resizableDoubleArray_ExpansionMode0, doubleArray0);
      // Undeclared exception!
      try { 
        resizableDoubleArray0.getElement(16);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test11_pred12()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      resizableDoubleArray0.setNumElements(2830);
      resizableDoubleArray0.discardFrontElements(5);
      assertEquals(2825, resizableDoubleArray0.getNumElements());
//    org.junit.Assert.assertEquals(1, resizableDoubleArray0.getNumElements());

}

@Test
  public void test12_pred13()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(1422, (-1445.726213460133));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // -1,445.226 is smaller than, or equal to, the minimum (1): contraction criteria smaller than one (-1,445.226).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria.
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test13_pred14()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.checkContractExpand(100.0, 100.0);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test14_pred15()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      double double0 = resizableDoubleArray0.substituteMostRecentElement(68);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(2, resizableDoubleArray0.getNumElements());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(3, resizableDoubleArray0.getCapacity());
      assertEquals(0.0, double0, 0.01);
}

@Test
  public void test15_pred16()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2432);
      resizableDoubleArray0.setElement(2432, (-303.16158));
      double double0 = resizableDoubleArray0.substituteMostRecentElement(3416.24336784);
      assertEquals(2433, resizableDoubleArray0.getNumElements());
      assertEquals((-303.16158), double0, 0.01);
//    org.junit.Assert.assertEquals(1, resizableDoubleArray0.getNumElements());

}

@Test
  public void test16_pred17()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      resizableDoubleArray0.setNumElements(2);
      resizableDoubleArray0.addElementRolling(2);
      int int0 = resizableDoubleArray0.getStartIndex();
      assertEquals(2, resizableDoubleArray0.getNumElements());
      assertEquals(1, int0);
}

@Test
  public void test17_pred18()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(3938);
      int int0 = resizableDoubleArray0.getNumElements();
      assertEquals(3938, resizableDoubleArray0.getCapacity());
      assertEquals(3938, int0);
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test18_pred19()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      resizableDoubleArray0.setNumElements(2);
      resizableDoubleArray0.getElements();
      assertEquals(2, resizableDoubleArray0.getNumElements());
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getNumElements());

}

@Test
  public void test19_pred20()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(274);
      resizableDoubleArray0.getElement(6);
      assertEquals(274, resizableDoubleArray0.getNumElements());
//    org.junit.Assert.assertEquals(1, resizableDoubleArray0.getNumElements());

}

@Test
  public void test20_pred21()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(2080);
      resizableDoubleArray0.addElement(2080);
      double double0 = resizableDoubleArray0.getElement(2080);
      assertEquals(2081, resizableDoubleArray0.getNumElements());
      assertEquals(2080.0, double0, 0.01);
//    org.junit.Assert.assertEquals(1, resizableDoubleArray0.getNumElements());

}

@Test
  public void test21_pred22()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[3];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(57, 57, 57, resizableDoubleArray_ExpansionMode0, doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = resizableDoubleArray0.copy();
      assertEquals(4, resizableDoubleArray1.getCapacity());
      assertEquals(57.0, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(3, resizableDoubleArray1.getNumElements());
      assertTrue(resizableDoubleArray1.equals((Object)resizableDoubleArray0));
//    org.junit.Assert.assertEquals(0, resizableDoubleArray1.getCapacity());

}

@Test
  public void test22_pred23()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(3938);
      resizableDoubleArray0.addElement(3938);
      StandardDeviation standardDeviation0 = new StandardDeviation();
      double double0 = resizableDoubleArray0.compute(standardDeviation0);
      assertEquals(3939, resizableDoubleArray0.getNumElements());
      assertEquals(62.74551979122924, double0, 0.01);
//    org.junit.Assert.assertEquals(1, resizableDoubleArray0.getNumElements());

}

@Test
  public void test23_pred24()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(401);
      SumOfLogs sumOfLogs0 = new SumOfLogs();
      resizableDoubleArray0.compute(sumOfLogs0);
      assertEquals(401, resizableDoubleArray0.getNumElements());
//    org.junit.Assert.assertEquals(1, resizableDoubleArray0.getNumElements());

}

@Test
  public void test24_pred25()  throws Throwable  {
      double[] doubleArray0 = new double[5];
      doubleArray0[0] = (double) 2;
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      double double0 = resizableDoubleArray0.addElementRolling(2.0);
      assertEquals(6, resizableDoubleArray0.getCapacity());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(5, resizableDoubleArray0.getNumElements());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(2.0, double0, 0.01);
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test25_pred26()  throws Throwable  {
      double[] doubleArray0 = new double[7];
      doubleArray0[0] = (-1.0);
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      double double0 = resizableDoubleArray0.addElementRolling((-158.0928));
      assertEquals((-1.0), double0, 0.01);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(8, resizableDoubleArray0.getCapacity());
      assertEquals(7, resizableDoubleArray0.getNumElements());
}

@Test
  public void test26_pred27()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.compute((MathArrays.Function) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test27_pred28()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      try { 
        resizableDoubleArray0.checkContractExpand((-3279.98181135), (-3279.98181135));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // -3,279.982 is smaller than, or equal to, the minimum (1): contraction criteria smaller than one (-3,279.982).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria.
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test28_pred29()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.addElements((double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test29_pred30()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray((ResizableDoubleArray) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
}

@Test
  public void test30_pred31()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.MULTIPLICATIVE;
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(857, (-2799.826555457084), 857, resizableDoubleArray_ExpansionMode0, doubleArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 857 is smaller than, or equal to, the minimum (1): expansion factor smaller than one (-2,799.827)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test31_pred32()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray((-1), (-1), (-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // initial capacity (-1) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test32_pred33()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(0, 0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // initial capacity (0) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test33_pred34()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray((-915));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // initial capacity (-915) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test34_pred35()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38, 38, 38, resizableDoubleArray_ExpansionMode0, doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = resizableDoubleArray0.copy();
      assertTrue(resizableDoubleArray1.equals((Object)resizableDoubleArray0));
      
      resizableDoubleArray1.addElementRolling(38);
      boolean boolean0 = resizableDoubleArray1.equals(resizableDoubleArray0);
      assertFalse(resizableDoubleArray1.equals((Object)resizableDoubleArray0));
      assertFalse(boolean0);
}

@Test
  public void test35_pred36()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(doubleArray0);
      resizableDoubleArray1.setElement(3938, 3938);
      resizableDoubleArray1.equals(resizableDoubleArray0);
      assertEquals(3939, resizableDoubleArray1.getCapacity());
//    org.junit.Assert.assertEquals(0, resizableDoubleArray1.getCapacity());

}

@Test
  public void test36_pred37()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.MULTIPLICATIVE;
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(3938, 2.5, 2.5, resizableDoubleArray_ExpansionMode0, doubleArray0);
      boolean boolean0 = resizableDoubleArray0.equals(resizableDoubleArray1);
      assertFalse(boolean0);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(3938, resizableDoubleArray1.getCapacity());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray1.getNumElements());
//    org.junit.Assert.assertTrue(boolean0);

}

@Test
  public void test37_pred38()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(1894, 1894);
      boolean boolean0 = resizableDoubleArray0.equals(resizableDoubleArray1);
      assertEquals(1894.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
      assertEquals(0, resizableDoubleArray1.getNumElements());
      assertEquals(1894, resizableDoubleArray1.getCapacity());
      assertFalse(boolean0);
      assertEquals(1894.5, resizableDoubleArray1.getContractionCriterion(), 0.01);
}

@Test
  public void test38_pred39()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      Object object0 = new Object();
      boolean boolean0 = resizableDoubleArray0.equals(object0);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertFalse(boolean0);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
}

@Test
  public void test39_pred40()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      boolean boolean0 = resizableDoubleArray0.equals(resizableDoubleArray0);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertTrue(boolean0);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
}

@Test
  public void test40_pred41()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      ResizableDoubleArray resizableDoubleArray1 = new ResizableDoubleArray(resizableDoubleArray0);
      boolean boolean0 = resizableDoubleArray1.equals(resizableDoubleArray0);
      assertEquals(16, resizableDoubleArray1.getCapacity());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(2.0, resizableDoubleArray1.getExpansionFactor(), 0.01);
      assertTrue(boolean0);
}

@Test
  public void test41_pred42()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[3];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(57, 57, 57, resizableDoubleArray_ExpansionMode0, doubleArray0);
      resizableDoubleArray0.expand();
      assertEquals(61, resizableDoubleArray0.getCapacity());
      
      resizableDoubleArray0.addElementRolling(57);
      assertEquals(4, resizableDoubleArray0.getCapacity());
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test42_pred43()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      try { 
        resizableDoubleArray0.setNumElements((-2392));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // index (-2,392) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test43_pred44()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.setElement((-28), (-28));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test44_pred45()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.getElement((-1852));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test45_pred46()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      // Undeclared exception!
      try { 
        resizableDoubleArray0.getElement(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test46_pred47()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.setNumElements(328);
      resizableDoubleArray0.discardMostRecentElements(4);
      assertEquals(324, resizableDoubleArray0.getNumElements());
//    org.junit.Assert.assertEquals(1, resizableDoubleArray0.getNumElements());

}

@Test
  public void test47_pred48()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      try { 
        resizableDoubleArray0.discardFrontElements((-504));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // cannot discard a negative number of elements (-504)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test48_pred49()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(1, 1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 1.5 is smaller than, or equal to, the minimum (1): expansion factor smaller than one (1)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test49_pred50()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(1, 1, 1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 1 is smaller than, or equal to, the minimum (1): contraction criteria smaller than one (1).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria.
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test50_pred51()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray(16, 16, (-1826.841634));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // -1,826.842 is smaller than the minimum (1): contraction criteria (-1,826.842) smaller than the expansion factor (16).  This would lead to a never ending loop of expansion and contraction as a newly expanded internal storage array would immediately satisfy the criteria for contraction.
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test51_pred52()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      try { 
        resizableDoubleArray0.substituteMostRecentElement(2.5);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // cannot substitute an element from an empty array
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test52_pred53()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.addElement(1337.497924321178);
      double double0 = resizableDoubleArray0.substituteMostRecentElement(1337.497924321178);
      assertEquals(1, resizableDoubleArray0.getNumElements());
      assertEquals(1337.497924321178, double0, 0.01);
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getNumElements());

}

@Test
  public void test53_pred54()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38);
      double double0 = resizableDoubleArray0.addElementRolling(38);
      assertEquals(1, resizableDoubleArray0.getCapacity());
      assertEquals(0.0, double0, 0.01);
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test54_pred55()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(870);
      resizableDoubleArray0.setNumElements(870);
      resizableDoubleArray0.addElement((-196.83991928171));
      double double0 = resizableDoubleArray0.getElement(870);
      assertEquals(871, resizableDoubleArray0.getNumElements());
      assertEquals((-196.83991928171), double0, 0.01);
//    org.junit.Assert.assertEquals(1, resizableDoubleArray0.getNumElements());

}

@Test
  public void test55_pred56()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.MULTIPLICATIVE;
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = null;
      try {
        resizableDoubleArray0 = new ResizableDoubleArray((-1421), (-1421), (-1421), resizableDoubleArray_ExpansionMode0, doubleArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // initial capacity (-1,421) is not positive
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test56_pred57()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray((double[]) null);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
}

@Test
  public void test57_pred58()  throws Throwable  {
      ResizableDoubleArray.ExpansionMode resizableDoubleArray_ExpansionMode0 = ResizableDoubleArray.ExpansionMode.ADDITIVE;
      double[] doubleArray0 = new double[3];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(57, 57, 57, resizableDoubleArray_ExpansionMode0, doubleArray0);
      resizableDoubleArray0.hashCode();
      assertEquals(57.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(3, resizableDoubleArray0.getNumElements());
      assertEquals(4, resizableDoubleArray0.getCapacity());
}

@Test
  public void test58_pred59()  throws Throwable  {
      double[] doubleArray0 = new double[10];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      // Undeclared exception!
      try { 
        resizableDoubleArray0.setElement(Integer.MAX_VALUE, Integer.MAX_VALUE);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test59_pred60()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      int int0 = resizableDoubleArray0.getNumElements();
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, int0);
}

@Test
  public void test60_pred61()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38);
      int int0 = resizableDoubleArray0.getCapacity();
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(38, int0);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
}

@Test
  public void test61_pred62()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      resizableDoubleArray0.discardFrontElements(0);
      assertEquals(1, resizableDoubleArray0.getCapacity());
//    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getCapacity());

}

@Test
  public void test62_pred63()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      double[] doubleArray0 = resizableDoubleArray0.getElements();
      assertEquals(0, doubleArray0.length);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(2.0, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(2, resizableDoubleArray0.getCapacity());
}

@Test
  public void test63_pred64()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      
      resizableDoubleArray0.contract();
      assertEquals(1, resizableDoubleArray0.getCapacity());
}

@Test
  public void test64_pred65()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      int int0 = resizableDoubleArray0.getStartIndex();
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2, resizableDoubleArray0.getCapacity());
      assertEquals(2.0, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, int0);
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getNumElements());

}

@Test
  public void test65_pred66()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38);
      resizableDoubleArray0.getExpansionMode();
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(38, resizableDoubleArray0.getCapacity());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
}

@Test
  public void test66_pred67()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(38);
      SumOfSquares sumOfSquares0 = new SumOfSquares();
      resizableDoubleArray0.compute(sumOfSquares0);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(38, resizableDoubleArray0.getCapacity());
}

@Test
  public void test67_pred68()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      double[] doubleArray0 = resizableDoubleArray0.getArrayRef();
      assertEquals(16, doubleArray0.length);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
}

@Test
  public void test68_pred69()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      try { 
        resizableDoubleArray0.discardMostRecentElements(3936);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // cannot discard 3,936 elements from a 0 elements array
         //
         verifyException("org.apache.commons.math4.util.ResizableDoubleArray", e);
      }
}

@Test
  public void test69_pred70()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray();
      double double0 = resizableDoubleArray0.getExpansionFactor();
      assertEquals(0, resizableDoubleArray0.getNumElements());
      assertEquals(2.0, double0, 0.01);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
    org.junit.Assert.assertEquals(0, resizableDoubleArray0.getNumElements());

}

@Test
  public void test70_pred71()  throws Throwable  {
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(2, 2.0, 2.0);
      double double0 = resizableDoubleArray0.getContractionCriterion();
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(2.0, double0, 0.01);
      assertEquals(2, resizableDoubleArray0.getCapacity());
      assertEquals(0, resizableDoubleArray0.getNumElements());
}

@Test
  public void test71_pred72()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ResizableDoubleArray resizableDoubleArray0 = new ResizableDoubleArray(doubleArray0);
      resizableDoubleArray0.clear();
      assertEquals(2.0, resizableDoubleArray0.getExpansionFactor(), 0.01);
      assertEquals(2.5, resizableDoubleArray0.getContractionCriterion(), 0.01);
      assertEquals(16, resizableDoubleArray0.getCapacity());
      assertEquals(0, resizableDoubleArray0.getNumElements());
}
}