/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 16 10:27:40 GMT 2025
 */

package org.apache.commons.math4.ode.events;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.analysis.solvers.IllinoisSolver;
import org.apache.commons.math4.analysis.solvers.MullerSolver2;
import org.apache.commons.math4.analysis.solvers.PegasusSolver;
import org.apache.commons.math4.analysis.solvers.UnivariateSolver;
import org.apache.commons.math4.ode.ExpandableStatefulODE;
import org.apache.commons.math4.ode.FirstOrderConverter;
import org.apache.commons.math4.ode.SecondOrderDifferentialEquations;
import org.apache.commons.math4.ode.events.EventFilter;
import org.apache.commons.math4.ode.events.EventHandler;
import org.apache.commons.math4.ode.events.EventState;
import org.apache.commons.math4.ode.events.FilterType;
import org.apache.commons.math4.ode.sampling.NordsieckStepInterpolator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EventState_ESTest extends EventState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      doReturn(2890.075958056263).when(eventHandler0).g(anyDouble() , any(double[].class));
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      double[] doubleArray0 = new double[3];
      eventFilter0.init(0.0, doubleArray0, 0.0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver(0.0, 0.0, 0.0);
      EventState eventState0 = new EventState(eventFilter0, 0.5, 1.0, 0, illinoisSolver0);
      eventState0.stepAccepted(0.0, doubleArray0);
      assertEquals(0.5, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(1.0, eventState0.getConvergence(), 0.01);
      assertEquals(0, eventState0.getMaxIterationCount());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_INCREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      MullerSolver2 mullerSolver2_0 = new MullerSolver2(550.0, 550.0);
      EventState eventState0 = new EventState(eventFilter0, 1822.21107824489, 1822.21107824489, 7, mullerSolver2_0);
      int int0 = eventState0.getMaxIterationCount();
      assertEquals(7, int0);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(1822.21107824489, eventState0.getMaxCheckInterval(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IllinoisSolver illinoisSolver0 = new IllinoisSolver((-928.0), (-928.0), (-1236));
      EventState eventState0 = new EventState((EventHandler) null, (-928.0), 427.0913171444327, (-1236), illinoisSolver0);
      int int0 = eventState0.getMaxIterationCount();
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals((-928.0), eventState0.getMaxCheckInterval(), 0.01);
      assertEquals((-1236), int0);
      assertEquals(427.0913171444327, eventState0.getConvergence(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver((-899), (-899));
      EventState eventState0 = new EventState(eventFilter0, 0.0, 0.0, (-899), illinoisSolver0);
      double double0 = eventState0.getMaxCheckInterval();
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(0.0, double0, 0.01);
      assertEquals((-899), eventState0.getMaxIterationCount());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_INCREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      MullerSolver2 mullerSolver2_0 = new MullerSolver2(550.0, 550.0);
      EventState eventState0 = new EventState(eventFilter0, 1822.21107824489, 1822.21107824489, 7, mullerSolver2_0);
      double double0 = eventState0.getMaxCheckInterval();
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(7, eventState0.getMaxIterationCount());
      assertEquals(1822.21107824489, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      EventState eventState0 = new EventState(eventFilter0, (-1033.706601), (-1033.706601), 0, (UnivariateSolver) null);
      eventState0.getEventHandler();
      assertEquals(0, eventState0.getMaxIterationCount());
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals((-1033.706601), eventState0.getMaxCheckInterval(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver((-1206.339073275));
      EventState eventState0 = new EventState(eventFilter0, 0.0, 0.0, 0, illinoisSolver0);
      double double0 = eventState0.getConvergence();
      assertEquals(0, eventState0.getMaxIterationCount());
      assertEquals(0.0, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PegasusSolver pegasusSolver0 = new PegasusSolver();
      EventState eventState0 = new EventState((EventHandler) null, 1444, 1444, 1444, pegasusSolver0);
      double[] doubleArray0 = new double[1];
      // Undeclared exception!
      try { 
        eventState0.stepAccepted(1444, doubleArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.ode.events.EventState", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PegasusSolver pegasusSolver0 = new PegasusSolver();
      EventState eventState0 = new EventState((EventHandler) null, (-1848068348), (-1848068348), (-1848068348), pegasusSolver0);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      // Undeclared exception!
      try { 
        eventState0.reinitializeBegin(nordsieckStepInterpolator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.ode.events.EventState", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MullerSolver2 mullerSolver2_0 = new MullerSolver2((-2531));
      EventState eventState0 = new EventState((EventHandler) null, 6.17225757562836, 2.0217439756338078E-10, (-2531), mullerSolver2_0);
      double[] doubleArray0 = new double[1];
      boolean boolean0 = eventState0.reset(2.0217439756338078E-10, doubleArray0);
      assertEquals((-2531), eventState0.getMaxIterationCount());
      assertEquals(2.0217439756338078E-10, eventState0.getConvergence(), 0.01);
      assertFalse(boolean0);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(6.17225757562836, eventState0.getMaxCheckInterval(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver((-1206.339073275));
      EventState eventState0 = new EventState(eventFilter0, 0.0, 0.0, 0, illinoisSolver0);
      boolean boolean0 = eventState0.stop();
      assertEquals(0, eventState0.getMaxIterationCount());
      assertFalse(boolean0);
      assertEquals(0.0, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      doReturn((-6.17225757562836)).when(eventHandler0).g(anyDouble() , any(double[].class));
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      double[] doubleArray0 = new double[8];
      eventFilter0.init(0.0, doubleArray0, 0.0);
      PegasusSolver pegasusSolver0 = new PegasusSolver(0.95, 0.0);
      EventState eventState0 = new EventState(eventFilter0, 0.0, 3297.0763734, 0, pegasusSolver0);
      eventState0.stepAccepted(Double.POSITIVE_INFINITY, doubleArray0);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(0.0, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(3297.0763734, eventState0.getConvergence(), 0.01);
      assertEquals(0, eventState0.getMaxIterationCount());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      PegasusSolver pegasusSolver0 = new PegasusSolver(0.95, 0.0);
      EventState eventState0 = new EventState(eventFilter0, 0.0, 3297.0763734, 0, pegasusSolver0);
      double double0 = eventState0.getEventTime();
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
      assertEquals(0.0, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(0, eventState0.getMaxIterationCount());
      assertEquals(3297.0763734, eventState0.getConvergence(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(eventHandler0).g(anyDouble() , any(double[].class));
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver(3290.5364627754257, (-855.7872), (-1748.555503306));
      EventState eventState0 = new EventState(eventFilter0, 3290.5364627754257, (-1748.555503306), 2048, illinoisSolver0);
      double[] doubleArray0 = new double[3];
      eventFilter0.init(1893.19124, doubleArray0, 3290.5364627754257);
      eventState0.stepAccepted(7.243267286265823E-142, doubleArray0);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      nordsieckStepInterpolator0.setSoftCurrentTime((-855.7872));
      boolean boolean0 = eventState0.evaluateStep(nordsieckStepInterpolator0);
      assertEquals(Double.POSITIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MullerSolver2 mullerSolver2_0 = new MullerSolver2((-2531));
      EventState eventState0 = new EventState((EventHandler) null, 6.17225757562836, 2.0217439756338078E-10, (-2531), mullerSolver2_0);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      // Undeclared exception!
      try { 
        eventState0.evaluateStep(nordsieckStepInterpolator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.ode.events.EventState", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MullerSolver2 mullerSolver2_0 = new MullerSolver2((-2531));
      EventState eventState0 = new EventState((EventHandler) null, (-2531), (-2531), 0, mullerSolver2_0);
      double double0 = eventState0.getMaxCheckInterval();
      assertEquals(0, eventState0.getMaxIterationCount());
      assertEquals((-2531.0), double0, 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MullerSolver2 mullerSolver2_0 = new MullerSolver2((-2531));
      EventState eventState0 = new EventState((EventHandler) null, 6.17225757562836, 2.0217439756338078E-10, (-2531), mullerSolver2_0);
      eventState0.getEventHandler();
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(6.17225757562836, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(2.0217439756338078E-10, eventState0.getConvergence(), 0.01);
      assertEquals((-2531), eventState0.getMaxIterationCount());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver(0.0, 0.0, 0.0);
      EventState eventState0 = new EventState(eventFilter0, 0.5, 1.0, 0, illinoisSolver0);
      int int0 = eventState0.getMaxIterationCount();
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(0.5, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(0, int0);
      assertEquals(1.0, eventState0.getConvergence(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver(3290.5364627754257, (-855.7872), (-1748.555503306));
      EventState eventState0 = new EventState(eventFilter0, 3290.5364627754257, (-1748.555503306), 2048, illinoisSolver0);
      double double0 = eventState0.getConvergence();
      assertEquals(1748.555503306, double0, 0.01);
      assertEquals(3290.5364627754257, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(2048, eventState0.getMaxIterationCount());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      EventState eventState0 = new EventState(eventFilter0, (-1033.706601), (-1033.706601), 0, (UnivariateSolver) null);
      SecondOrderDifferentialEquations secondOrderDifferentialEquations0 = mock(SecondOrderDifferentialEquations.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(secondOrderDifferentialEquations0).getDimension();
      FirstOrderConverter firstOrderConverter0 = new FirstOrderConverter(secondOrderDifferentialEquations0);
      ExpandableStatefulODE expandableStatefulODE0 = new ExpandableStatefulODE(firstOrderConverter0);
      eventState0.setExpandable(expandableStatefulODE0);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      // Undeclared exception!
      try { 
        eventState0.reinitializeBegin(nordsieckStepInterpolator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

//@Test
//  public void test13_pred1()  throws Throwable  {
//
//    try {      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
//      doReturn(0.0).when(eventHandler0).g(anyDouble() , any(double[].class));
//      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
//      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
//      IllinoisSolver illinoisSolver0 = new IllinoisSolver(3290.5364627754257, (-855.7872), (-1748.555503306));
//      EventState eventState0 = new EventState(eventFilter0, 3290.5364627754257, (-1748.555503306), 2048, illinoisSolver0);
//      double[] doubleArray0 = new double[3];
//      eventFilter0.init(1893.19124, doubleArray0, 3290.5364627754257);
//      eventState0.stepAccepted(7.243267286265823E-142, doubleArray0);
//      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
//      nordsieckStepInterpolator0.setSoftCurrentTime((-855.7872));
//      boolean boolean0 = eventState0.evaluateStep(nordsieckStepInterpolator0);
//      assertEquals(Double.POSITIVE_INFINITY, eventState0.getEventTime(), 0.01);
//      assertFalse(boolean0);
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
//    } catch (Exception e) {
//        // expected exception predicted by TOGA
//    }
//
//}

@Test
  public void test14_pred2()  throws Throwable  {
      MullerSolver2 mullerSolver2_0 = new MullerSolver2((-2531));
      EventState eventState0 = new EventState((EventHandler) null, 6.17225757562836, 2.0217439756338078E-10, (-2531), mullerSolver2_0);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      // Undeclared exception!
      try { 
        eventState0.evaluateStep(nordsieckStepInterpolator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.ode.events.EventState", e);
      }
}
}