/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 16 14:35:43 GMT 2025
 */

package org.apache.commons.math3.stat.correlation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math3.linear.Array2DRowRealMatrix;
import org.apache.commons.math3.linear.BlockRealMatrix;
import org.apache.commons.math3.linear.DiagonalMatrix;
import org.apache.commons.math3.linear.RealMatrix;
import org.apache.commons.math3.stat.correlation.Covariance;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Covariance_ESTest extends Covariance_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      double[][] doubleArray1 = new double[3][9];
      doubleArray1[0] = doubleArray0;
      doubleArray1[1] = doubleArray0;
      doubleArray1[2] = doubleArray0;
      Covariance covariance0 = new Covariance(doubleArray1, false);
      double[] doubleArray2 = new double[0];
      try { 
        covariance0.covariance(doubleArray2, doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 != 4
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      double[][] doubleArray0 = new double[2][7];
      Covariance covariance0 = new Covariance(doubleArray0, true);
      assertEquals(2, covariance0.getN());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      int int0 = covariance0.getN();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      covariance0.getCovarianceMatrix();
      assertEquals(0, covariance0.getN());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[0] = 1780.75;
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0, true);
      double double0 = covariance0.covariance(doubleArray0, doubleArray0, false);
      assertEquals(792767.640625, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      double[][] doubleArray0 = new double[2][7];
      double[] doubleArray1 = new double[3];
      doubleArray1[2] = (-1677.21672);
      doubleArray0[0] = doubleArray1;
      double[] doubleArray2 = new double[3];
      doubleArray2[1] = (-1677.21672);
      doubleArray0[1] = doubleArray2;
      Covariance covariance0 = new Covariance(doubleArray0);
      double double0 = covariance0.covariance(doubleArray1, doubleArray2, true);
      assertEquals((-468842.65430792636), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[0] = 1780.75;
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0, true);
      double double0 = covariance0.covariance(doubleArray0, doubleArray0);
      assertEquals(1585535.28125, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (-1139.00598332);
      double[] doubleArray1 = new double[3];
      doubleArray1[1] = (-1139.00598332);
      double double0 = covariance0.covariance(doubleArray0, doubleArray1);
      assertEquals(0, covariance0.getN());
      assertEquals((-216222.43833979336), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      double[] doubleArray0 = new double[8];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0);
      double[][] doubleArray1 = new double[5][2];
      doubleArray1[0] = doubleArray0;
      doubleArray1[1] = doubleArray0;
      doubleArray1[2] = doubleArray0;
      doubleArray1[3] = doubleArray0;
      doubleArray1[4] = doubleArray0;
      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(doubleArray1, false);
      assertEquals(8, realMatrix0.getRowDimension());
      assertEquals(8, realMatrix0.getColumnDimension());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0);
      double[][] doubleArray1 = new double[3][7];
      doubleArray1[0] = doubleArray0;
      doubleArray1[1] = doubleArray0;
      doubleArray1[2] = doubleArray0;
      BlockRealMatrix blockRealMatrix0 = (BlockRealMatrix)covariance0.computeCovarianceMatrix(doubleArray1);
      assertFalse(blockRealMatrix0.isTransposable());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      double[][] doubleArray0 = new double[2][7];
      double[] doubleArray1 = new double[3];
      doubleArray0[0] = doubleArray1;
      doubleArray0[1] = doubleArray1;
      Covariance covariance0 = new Covariance(doubleArray0);
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray1, true);
      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(diagonalMatrix0, true);
      assertEquals(3, realMatrix0.getColumnDimension());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      double[][] doubleArray0 = new double[8][8];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0);
      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(array2DRowRealMatrix0);
      assertEquals(8, realMatrix0.getColumnDimension());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.covariance((double[]) null, (double[]) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[] doubleArray0 = new double[0];
      try { 
        covariance0.covariance(doubleArray0, doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 0 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      double[][] doubleArray0 = new double[8][8];
      Covariance covariance0 = new Covariance(doubleArray0);
      // Undeclared exception!
      try { 
        covariance0.covariance((double[]) null, (double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = new Covariance();
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 1 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      double[][] doubleArray0 = new double[56][8];
      Covariance covariance0 = new Covariance(doubleArray0);
      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(doubleArray0, true);
      assertEquals(8, realMatrix0.getColumnDimension());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[1][4];
      double[] doubleArray1 = new double[0];
      doubleArray0[0] = doubleArray1;
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.linear.AbstractRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0);
      double[][] doubleArray1 = new double[3][7];
      doubleArray1[0] = doubleArray0;
      try { 
        covariance0.computeCovarianceMatrix(doubleArray1, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 4 != 7
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix((double[][]) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[0][8];
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[1][6];
      double[] doubleArray1 = new double[0];
      doubleArray0[0] = doubleArray1;
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.linear.AbstractRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[5][6];
      double[] doubleArray1 = new double[0];
      doubleArray0[0] = doubleArray1;
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 != 6
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix((double[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[0][6];
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0, true);
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 1 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(78, 78);
      // Undeclared exception!
      covariance0.computeCovarianceMatrix(array2DRowRealMatrix0, true);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix();
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.linear.AbstractRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix((RealMatrix) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[] doubleArray0 = new double[0];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0, true);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(61, 1437);
      RealMatrix realMatrix0 = array2DRowRealMatrix0.getRowMatrix(1);
      try { 
        covariance0.computeCovarianceMatrix(realMatrix0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 1 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix();
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.linear.AbstractRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix((RealMatrix) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[] doubleArray0 = new double[0];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      double[][] doubleArray0 = new double[6][4];
      double[] doubleArray1 = new double[5];
      doubleArray0[4] = doubleArray1;
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 4 != 5
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      double[][] doubleArray0 = new double[0][5];
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0, true);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // insufficient data: only 1 rows and 8 columns.
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      double[] doubleArray0 = new double[8];
      double[][] doubleArray1 = new double[7][5];
      doubleArray1[0] = doubleArray0;
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 8 != 5
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      double[][] doubleArray0 = new double[0][3];
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(701, 701);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0, true);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance((RealMatrix) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(array2DRowRealMatrix0, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix();
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(array2DRowRealMatrix0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // insufficient data: only 0 rows and 0 columns.
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance((RealMatrix) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(array2DRowRealMatrix0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      double[][] doubleArray0 = new double[2][7];
      double[] doubleArray1 = new double[3];
      doubleArray0[0] = doubleArray1;
      doubleArray0[1] = doubleArray1;
      Covariance covariance0 = new Covariance(doubleArray0);
      double double0 = covariance0.covariance(doubleArray1, doubleArray0[0], true);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      double[][] doubleArray0 = new double[8][8];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0);
      double[] doubleArray1 = new double[0];
      try { 
        covariance0.covariance(doubleArray1, doubleArray1, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 0 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(array2DRowRealMatrix0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // insufficient data: only 4 rows and 1 columns.
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // insufficient data: only 1 rows and 8 columns.
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = new Covariance();
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 1 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      double[][] doubleArray0 = new double[4][8];
      Covariance covariance0 = new Covariance(doubleArray0);
      double[] doubleArray1 = new double[1];
      double[] doubleArray2 = new double[0];
      try { 
        covariance0.covariance(doubleArray1, doubleArray2, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1 != 0
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0, true);
      double double0 = covariance0.covariance(doubleArray0, doubleArray0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      double[][] doubleArray0 = new double[56][8];
      Covariance covariance0 = new Covariance(doubleArray0);
      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(doubleArray0);
      assertEquals(8, realMatrix0.getColumnDimension());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      double[][] doubleArray0 = new double[8][8];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0);
      RealMatrix realMatrix0 = covariance0.getCovarianceMatrix();
      assertEquals(8, realMatrix0.getColumnDimension());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      BlockRealMatrix blockRealMatrix0 = new BlockRealMatrix(1024, 1024);
      // Undeclared exception!
      covariance0.computeCovarianceMatrix(blockRealMatrix0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0, true);
      int int0 = covariance0.getN();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(2583, 2583);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0);
  }

@Test
  public void test00_pred1()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      double[][] doubleArray1 = new double[3][9];
      doubleArray1[0] = doubleArray0;
      doubleArray1[1] = doubleArray0;
      doubleArray1[2] = doubleArray0;
      Covariance covariance0 = new Covariance(doubleArray1, false);
      double[] doubleArray2 = new double[0];
      try { 
        covariance0.covariance(doubleArray2, doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 != 4
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test01_pred2()  throws Throwable  {
      double[][] doubleArray0 = new double[2][7];
      Covariance covariance0 = new Covariance(doubleArray0, true);
      assertEquals(2, covariance0.getN());
//    org.junit.Assert.assertEquals(0, covariance0.getN());

}

@Test
  public void test02_pred3()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      int int0 = covariance0.getN();
      assertEquals(0, int0);
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test03_pred4()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      covariance0.getCovarianceMatrix();
      assertEquals(0, covariance0.getN());
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test04_pred5()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[0] = 1780.75;
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0, true);
      double double0 = covariance0.covariance(doubleArray0, doubleArray0, false);
      assertEquals(792767.640625, double0, 0.01);
}

@Test
  public void test05_pred6()  throws Throwable  {
      double[][] doubleArray0 = new double[2][7];
      double[] doubleArray1 = new double[3];
      doubleArray1[2] = (-1677.21672);
      doubleArray0[0] = doubleArray1;
      double[] doubleArray2 = new double[3];
      doubleArray2[1] = (-1677.21672);
      doubleArray0[1] = doubleArray2;
      Covariance covariance0 = new Covariance(doubleArray0);
      double double0 = covariance0.covariance(doubleArray1, doubleArray2, true);
      assertEquals((-468842.65430792636), double0, 0.01);
}

@Test
  public void test06_pred7()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[0] = 1780.75;
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0, true);
      double double0 = covariance0.covariance(doubleArray0, doubleArray0);
      assertEquals(1585535.28125, double0, 0.01);
}

@Test
  public void test07_pred8()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (-1139.00598332);
      double[] doubleArray1 = new double[3];
      doubleArray1[1] = (-1139.00598332);
      double double0 = covariance0.covariance(doubleArray0, doubleArray1);
      assertEquals(0, covariance0.getN());
      assertEquals((-216222.43833979336), double0, 0.01);
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test08_pred9()  throws Throwable  {

    try {      double[] doubleArray0 = new double[8];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0);
      double[][] doubleArray1 = new double[5][2];
      doubleArray1[0] = doubleArray0;
      doubleArray1[1] = doubleArray0;
      doubleArray1[2] = doubleArray0;
      doubleArray1[3] = doubleArray0;
      doubleArray1[4] = doubleArray0;
      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(doubleArray1, false);
      assertEquals(8, realMatrix0.getRowDimension());
      assertEquals(8, realMatrix0.getColumnDimension());
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test09_pred10()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0);
      double[][] doubleArray1 = new double[3][7];
      doubleArray1[0] = doubleArray0;
      doubleArray1[1] = doubleArray0;
      doubleArray1[2] = doubleArray0;
      BlockRealMatrix blockRealMatrix0 = (BlockRealMatrix)covariance0.computeCovarianceMatrix(doubleArray1);
      assertFalse(blockRealMatrix0.isTransposable());
    org.junit.Assert.assertFalse(blockRealMatrix0.isTransposable());

}

//@Test
//  public void test10_pred11()  throws Throwable  {
//      double[][] doubleArray0 = new double[2][7];
//      double[] doubleArray1 = new double[3];
//      doubleArray0[0] = doubleArray1;
//      doubleArray0[1] = doubleArray1;
//      Covariance covariance0 = new Covariance(doubleArray0);
//      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray1, true);
//      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(diagonalMatrix0, true);
//      assertEquals(3, realMatrix0.getColumnDimension());
//    org.junit.Assert.assertEquals(0, realMatrix0.getColumnDimension());
//
//}

//@Test
//  public void test11_pred12()  throws Throwable  {
//      double[][] doubleArray0 = new double[8][8];
//      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
//      Covariance covariance0 = new Covariance(array2DRowRealMatrix0);
//      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(array2DRowRealMatrix0);
//      assertEquals(8, realMatrix0.getColumnDimension());
//    org.junit.Assert.assertEquals(1, realMatrix0.getColumnDimension());
//
//}

@Test
  public void test12_pred13()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.covariance((double[]) null, (double[]) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test13_pred14()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      double[] doubleArray0 = new double[0];
      try { 
        covariance0.covariance(doubleArray0, doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 0 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test14_pred15()  throws Throwable  {

    try {      double[][] doubleArray0 = new double[8][8];
      Covariance covariance0 = new Covariance(doubleArray0);
      // Undeclared exception!
      try { 
        covariance0.covariance((double[]) null, (double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test15_pred16()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = new Covariance();
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 1 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test16_pred17()  throws Throwable  {
      double[][] doubleArray0 = new double[56][8];
      Covariance covariance0 = new Covariance(doubleArray0);
      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(doubleArray0, true);
      assertEquals(8, realMatrix0.getColumnDimension());
//    org.junit.Assert.assertEquals(0, realMatrix0.getColumnDimension());

}

@Test
  public void test17_pred18()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[1][4];
      double[] doubleArray1 = new double[0];
      doubleArray0[0] = doubleArray1;
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.linear.AbstractRealMatrix", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test18_pred19()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0);
      double[][] doubleArray1 = new double[3][7];
      doubleArray1[0] = doubleArray0;
      try { 
        covariance0.computeCovarianceMatrix(doubleArray1, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 4 != 7
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
}

@Test
  public void test19_pred20()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix((double[][]) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test20_pred21()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[0][8];
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test21_pred22()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[1][6];
      double[] doubleArray1 = new double[0];
      doubleArray0[0] = doubleArray1;
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.linear.AbstractRealMatrix", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test22_pred23()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[5][6];
      double[] doubleArray1 = new double[0];
      doubleArray0[0] = doubleArray1;
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 != 6
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test23_pred24()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix((double[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test24_pred25()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      double[][] doubleArray0 = new double[0][6];
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test25_pred26()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0, true);
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 1 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test26_pred27()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(78, 78);
      // Undeclared exception!
      covariance0.computeCovarianceMatrix(array2DRowRealMatrix0, true);
}

@Test
  public void test27_pred28()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix();
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.linear.AbstractRealMatrix", e);
      }
}

@Test
  public void test28_pred29()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix((RealMatrix) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test29_pred30()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[] doubleArray0 = new double[0];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0, true);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
}

@Test
  public void test30_pred31()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(61, 1437);
      RealMatrix realMatrix0 = array2DRowRealMatrix0.getRowMatrix(1);
      try { 
        covariance0.computeCovarianceMatrix(realMatrix0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 1 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test31_pred32()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix();
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.linear.AbstractRealMatrix", e);
      }
}

@Test
  public void test32_pred33()  throws Throwable  {

    try {      Covariance covariance0 = new Covariance();
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix((RealMatrix) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
//        org.junit.Assert.fail("Expected exception predicted by TOGA");
    } catch (Exception e) {
        // expected exception predicted by TOGA
    }

}

@Test
  public void test33_pred34()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      double[] doubleArray0 = new double[0];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      // Undeclared exception!
      try { 
        covariance0.computeCovarianceMatrix(array2DRowRealMatrix0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
}

@Test
  public void test34_pred35()  throws Throwable  {
      double[][] doubleArray0 = new double[6][4];
      double[] doubleArray1 = new double[5];
      doubleArray0[4] = doubleArray1;
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 4 != 5
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
}

@Test
  public void test35_pred36()  throws Throwable  {
      double[][] doubleArray0 = new double[0][5];
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0, true);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
}

@Test
  public void test36_pred37()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // insufficient data: only 1 rows and 8 columns.
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test37_pred38()  throws Throwable  {
      double[] doubleArray0 = new double[8];
      double[][] doubleArray1 = new double[7][5];
      doubleArray1[0] = doubleArray0;
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 8 != 5
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
}

@Test
  public void test38_pred39()  throws Throwable  {
      double[][] doubleArray0 = new double[0][3];
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math3.linear.BlockRealMatrix", e);
      }
}

@Test
  public void test39_pred40()  throws Throwable  {
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(701, 701);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0, true);
}

@Test
  public void test40_pred41()  throws Throwable  {
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance((RealMatrix) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test41_pred42()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(array2DRowRealMatrix0, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
}

@Test
  public void test42_pred43()  throws Throwable  {
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix();
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(array2DRowRealMatrix0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // insufficient data: only 0 rows and 0 columns.
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test43_pred44()  throws Throwable  {
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance((RealMatrix) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test44_pred45()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(array2DRowRealMatrix0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
}

@Test
  public void test45_pred46()  throws Throwable  {
      double[][] doubleArray0 = new double[2][7];
      double[] doubleArray1 = new double[3];
      doubleArray0[0] = doubleArray1;
      doubleArray0[1] = doubleArray1;
      Covariance covariance0 = new Covariance(doubleArray0);
      double double0 = covariance0.covariance(doubleArray1, doubleArray0[0], true);
      assertEquals(0.0, double0, 0.01);
}

@Test
  public void test46_pred47()  throws Throwable  {
      double[][] doubleArray0 = new double[8][8];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0);
      double[] doubleArray1 = new double[0];
      try { 
        covariance0.covariance(doubleArray1, doubleArray1, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 0 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test47_pred48()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(array2DRowRealMatrix0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // insufficient data: only 4 rows and 1 columns.
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test48_pred49()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = null;
      try {
        covariance0 = new Covariance(doubleArray0, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // insufficient data: only 1 rows and 8 columns.
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test49_pred50()  throws Throwable  {
      double[][] doubleArray0 = new double[1][8];
      Covariance covariance0 = new Covariance();
      try { 
        covariance0.computeCovarianceMatrix(doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // sample contains 1 observed points, at least 2 are required
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test50_pred51()  throws Throwable  {
      double[][] doubleArray0 = new double[4][8];
      Covariance covariance0 = new Covariance(doubleArray0);
      double[] doubleArray1 = new double[1];
      double[] doubleArray2 = new double[0];
      try { 
        covariance0.covariance(doubleArray1, doubleArray2, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1 != 0
         //
         verifyException("org.apache.commons.math3.stat.correlation.Covariance", e);
      }
}

@Test
  public void test51_pred52()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0, true);
      double double0 = covariance0.covariance(doubleArray0, doubleArray0);
      assertEquals(0.0, double0, 0.01);
}

@Test
  public void test52_pred53()  throws Throwable  {
      double[][] doubleArray0 = new double[56][8];
      Covariance covariance0 = new Covariance(doubleArray0);
      RealMatrix realMatrix0 = covariance0.computeCovarianceMatrix(doubleArray0);
      assertEquals(8, realMatrix0.getColumnDimension());
//    org.junit.Assert.assertEquals(0, realMatrix0.getColumnDimension());

}

@Test
  public void test53_pred54()  throws Throwable  {
      double[][] doubleArray0 = new double[8][8];
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0);
      RealMatrix realMatrix0 = covariance0.getCovarianceMatrix();
      assertEquals(8, realMatrix0.getColumnDimension());
//    org.junit.Assert.assertEquals(0, realMatrix0.getColumnDimension());

}

@Test
  public void test54_pred55()  throws Throwable  {
      Covariance covariance0 = new Covariance();
      BlockRealMatrix blockRealMatrix0 = new BlockRealMatrix(1024, 1024);
      // Undeclared exception!
      covariance0.computeCovarianceMatrix(blockRealMatrix0);
}

@Test
  public void test55_pred56()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      DiagonalMatrix diagonalMatrix0 = new DiagonalMatrix(doubleArray0);
      Covariance covariance0 = new Covariance(diagonalMatrix0, true);
      int int0 = covariance0.getN();
      assertEquals(2, int0);
//    org.junit.Assert.assertEquals(1, int0);

}

@Test
  public void test56_pred57()  throws Throwable  {
      Array2DRowRealMatrix array2DRowRealMatrix0 = new Array2DRowRealMatrix(2583, 2583);
      Covariance covariance0 = new Covariance(array2DRowRealMatrix0);
}
}