/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 16 08:16:57 GMT 2025
 */

package org.apache.commons.math3.distribution;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math3.distribution.EnumeratedRealDistribution;
import org.apache.commons.math3.random.MersenneTwister;
import org.apache.commons.math3.random.RandomAdaptor;
import org.apache.commons.math3.random.RandomGenerator;
import org.apache.commons.math3.random.Well1024a;
import org.apache.commons.math3.random.Well19937c;
import org.apache.commons.math3.random.Well44497a;
import org.apache.commons.math3.random.Well44497b;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EnumeratedRealDistribution_ESTest extends EnumeratedRealDistribution_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Well44497b well44497b0 = new Well44497b();
      double[] doubleArray0 = new double[7];
      doubleArray0[0] = (double) 1L;
      doubleArray0[2] = 664.78096549;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(well44497b0, doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.getSupportLowerBound();
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = 2056.0;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.cumulativeProbability(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      Well44497a well44497a0 = new Well44497a(2781);
      double[] doubleArray1 = new double[4];
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution(well44497a0, doubleArray0, doubleArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 4 != 2
         //
         verifyException("org.apache.commons.math3.distribution.EnumeratedRealDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      double[] doubleArray1 = new double[1];
      doubleArray1[0] = 3577.5468;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray1);
      double double0 = enumeratedRealDistribution0.sample();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      double[] doubleArray0 = new double[9];
      doubleArray0[0] = (double) 1L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.probability((double) 1L);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      double[] doubleArray0 = new double[3];
      double[] doubleArray1 = new double[3];
      doubleArray1[0] = (double) 1L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray1);
      double double0 = enumeratedRealDistribution0.getSupportUpperBound();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = 2055.273161033948;
      int[] intArray0 = new int[3];
      Well1024a well1024a0 = new Well1024a(intArray0);
      double[] doubleArray1 = new double[2];
      doubleArray1[1] = (double) (-91);
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(well1024a0, doubleArray1, doubleArray0);
      double double0 = enumeratedRealDistribution0.getSupportUpperBound();
      assertEquals((-91.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      double[] doubleArray1 = new double[1];
      doubleArray1[0] = 3577.5468;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray1);
      double double0 = enumeratedRealDistribution0.getSupportLowerBound();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[0] = 1.0;
      Well19937c well19937c0 = new Well19937c((int[]) null);
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(well19937c0, doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.getNumericalVariance();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Well44497b well44497b0 = new Well44497b();
      double[] doubleArray0 = new double[7];
      doubleArray0[0] = (double) 1L;
      doubleArray0[2] = 664.78096549;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(well44497b0, doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.getNumericalVariance();
      assertEquals(660.7929724298301, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      double[] doubleArray0 = new double[9];
      doubleArray0[0] = (double) 1L;
      doubleArray0[1] = (double) 1L;
      doubleArray0[2] = (double) 1L;
      doubleArray0[3] = (double) 1L;
      doubleArray0[4] = (double) 1L;
      doubleArray0[5] = (double) 1L;
      doubleArray0[6] = (double) 1L;
      doubleArray0[7] = (double) 1L;
      doubleArray0[8] = (double) 1L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.getNumericalVariance();
      assertEquals((-2.220446049250313E-16), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      double[] doubleArray1 = new double[1];
      doubleArray1[0] = 3577.5468;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray1);
      double double0 = enumeratedRealDistribution0.getNumericalMean();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a(4294967295L);
      RandomAdaptor randomAdaptor0 = new RandomAdaptor(well44497a0);
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 4294967295L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(randomAdaptor0, doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.density(Double.NEGATIVE_INFINITY);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      double[] doubleArray0 = new double[21];
      doubleArray0[1] = 5.166756209802596;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution((RandomGenerator) null, doubleArray0, doubleArray0);
      // Undeclared exception!
      try { 
        enumeratedRealDistribution0.sample();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.distribution.EnumeratedDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // array sums to zero
         //
         verifyException("org.apache.commons.math3.util.MathArrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      doubleArray0[0] = Double.NEGATIVE_INFINITY;
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -\u221E is smaller than the minimum (0)
         //
         verifyException("org.apache.commons.math3.distribution.EnumeratedDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution((double[]) null, (double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.distribution.EnumeratedRealDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      double[] doubleArray0 = new double[10];
      Well1024a well1024a0 = new Well1024a();
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution(well1024a0, doubleArray0, doubleArray0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // array sums to zero
         //
         verifyException("org.apache.commons.math3.util.MathArrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a((-1629L));
      double[] doubleArray0 = new double[1];
      doubleArray0[0] = (double) (-1629L);
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution(well44497a0, doubleArray0, doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -1,629 is smaller than the minimum (0)
         //
         verifyException("org.apache.commons.math3.distribution.EnumeratedDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      Well44497a well44497a0 = new Well44497a();
      double[] doubleArray1 = new double[0];
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution(well44497a0, doubleArray0, doubleArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 != 1
         //
         verifyException("org.apache.commons.math3.distribution.EnumeratedRealDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MersenneTwister mersenneTwister0 = new MersenneTwister((-929L));
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution(mersenneTwister0, (double[]) null, (double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.distribution.EnumeratedRealDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = 2055.273161033948;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.probability(Double.NEGATIVE_INFINITY);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = 2055.273161033948;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.getSupportUpperBound();
      assertEquals(2055.273161033948, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a();
      RandomAdaptor randomAdaptor0 = new RandomAdaptor(well44497a0);
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 4294967295L;
      doubleArray0[1] = (double) 4294967295L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(randomAdaptor0, doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.getSupportLowerBound();
      assertEquals(4.294967295E9, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a();
      RandomAdaptor randomAdaptor0 = new RandomAdaptor(well44497a0);
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 4294967295L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(randomAdaptor0, doubleArray0, doubleArray0);
      // Undeclared exception!
      try { 
        enumeratedRealDistribution0.inverseCumulativeProbability(0.3333333333333333);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [4,294,967,295, 4,294,967,295]
         //
         verifyException("org.apache.commons.math3.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a();
      RandomAdaptor randomAdaptor0 = new RandomAdaptor(well44497a0);
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 4294967295L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(randomAdaptor0, doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.getNumericalMean();
      assertEquals(4.294967295E9, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a();
      RandomAdaptor randomAdaptor0 = new RandomAdaptor(well44497a0);
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 4294967295L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(randomAdaptor0, doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.cumulativeProbability(4118.8971);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = 2055.273161033948;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.cumulativeProbability(2731.6123691687);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      double[] doubleArray0 = new double[10];
      double[] doubleArray1 = new double[1];
      EnumeratedRealDistribution enumeratedRealDistribution0 = null;
      try {
        enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1 != 10
         //
         verifyException("org.apache.commons.math3.distribution.EnumeratedRealDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      double[] doubleArray0 = new double[9];
      doubleArray0[0] = (double) 1L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      boolean boolean0 = enumeratedRealDistribution0.isSupportUpperBoundInclusive();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a();
      RandomAdaptor randomAdaptor0 = new RandomAdaptor(well44497a0);
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 4294967295L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(randomAdaptor0, doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.sample();
      assertEquals(4.294967295E9, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Well44497b well44497b0 = new Well44497b();
      double[] doubleArray0 = new double[7];
      doubleArray0[0] = (double) 1L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(well44497b0, doubleArray0, doubleArray0);
      boolean boolean0 = enumeratedRealDistribution0.isSupportLowerBoundInclusive();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = 2055.273161033948;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      boolean boolean0 = enumeratedRealDistribution0.isSupportConnected();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = 2055.273161033948;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(doubleArray0, doubleArray0);
      double double0 = enumeratedRealDistribution0.density(2055.273161033948);
      assertEquals(1.0, double0, 0.01);
  }

@Test
  public void test24_pred1()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a();
      RandomAdaptor randomAdaptor0 = new RandomAdaptor(well44497a0);
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 4294967295L;
      EnumeratedRealDistribution enumeratedRealDistribution0 = new EnumeratedRealDistribution(randomAdaptor0, doubleArray0, doubleArray0);
      // Undeclared exception!
      try { 
        enumeratedRealDistribution0.inverseCumulativeProbability(0.3333333333333333);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [4,294,967,295, 4,294,967,295]
         //
         verifyException("org.apache.commons.math3.analysis.solvers.UnivariateSolverUtils", e);
      }
}
}