/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 16 10:20:47 GMT 2025
 */

package org.apache.commons.math4.analysis.solvers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.analysis.UnivariateFunction;
import org.apache.commons.math4.analysis.function.Acos;
import org.apache.commons.math4.analysis.function.Atanh;
import org.apache.commons.math4.analysis.function.Cbrt;
import org.apache.commons.math4.analysis.function.Ceil;
import org.apache.commons.math4.analysis.function.Cos;
import org.apache.commons.math4.analysis.function.Cosh;
import org.apache.commons.math4.analysis.function.Expm1;
import org.apache.commons.math4.analysis.function.Inverse;
import org.apache.commons.math4.analysis.function.Logit;
import org.apache.commons.math4.analysis.function.Rint;
import org.apache.commons.math4.analysis.function.Sigmoid;
import org.apache.commons.math4.analysis.function.Signum;
import org.apache.commons.math4.analysis.function.Sinc;
import org.apache.commons.math4.analysis.function.Tanh;
import org.apache.commons.math4.analysis.polynomials.PolynomialFunction;
import org.apache.commons.math4.analysis.polynomials.PolynomialFunctionLagrangeForm;
import org.apache.commons.math4.analysis.solvers.AllowedSolution;
import org.apache.commons.math4.analysis.solvers.BracketedUnivariateSolver;
import org.apache.commons.math4.analysis.solvers.BracketingNthOrderBrentSolver;
import org.apache.commons.math4.analysis.solvers.PegasusSolver;
import org.apache.commons.math4.analysis.solvers.RegulaFalsiSolver;
import org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UnivariateSolverUtils_ESTest extends UnivariateSolverUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      boolean boolean0 = UnivariateSolverUtils.isSequence(777.677, 3394, 3394);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      boolean boolean0 = UnivariateSolverUtils.isSequence((-1089.963), (-1089.963), Double.NaN);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Signum signum0 = new Signum();
      assertNotNull(signum0);
      
      boolean boolean0 = UnivariateSolverUtils.isBracketing(signum0, (-281.97026778), 0.0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Sigmoid sigmoid0 = new Sigmoid();
      assertNotNull(sigmoid0);
      
      boolean boolean0 = UnivariateSolverUtils.isBracketing(sigmoid0, (-1372.5510528), (-1372.5510528));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, (-872.79967649875), (-1746.0993529975), (-561.6440526859524));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [-1,746.099, -561.644], values: [\uFFFD, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Cbrt cbrt0 = new Cbrt();
      assertNotNull(cbrt0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) cbrt0, Double.NaN, (double) 1, Double.NaN, (double) 1, Double.NaN, 1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [\uFFFD, \uFFFD], values: [\uFFFD, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      PolynomialFunction polynomialFunction0 = new PolynomialFunction(doubleArray0);
      assertEquals(0, polynomialFunction0.degree());
      assertNotNull(polynomialFunction0);
      assertArrayEquals(new double[] {0.0, 0.0}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) polynomialFunction0, 932.0102211, 537.588835750331, (-2273.30145656), 0.0, 0.0, 986);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RegulaFalsiSolver regulaFalsiSolver0 = new RegulaFalsiSolver(0.0);
      assertEquals(1.0E-14, regulaFalsiSolver0.getRelativeAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMin(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(1.0E-15, regulaFalsiSolver0.getFunctionValueAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMax(), 0.01);
      assertNotNull(regulaFalsiSolver0);
      
      Ceil ceil0 = new Ceil();
      assertNotNull(ceil0);
      
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      double double0 = UnivariateSolverUtils.forceSide(2376, ceil0, regulaFalsiSolver0, 0.0, 2388.7713974316, 0.935440928572949, allowedSolution0);
      assertEquals(1.0E-14, regulaFalsiSolver0.getRelativeAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals(2388.7713974316, regulaFalsiSolver0.getMin(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(1.0E-15, regulaFalsiSolver0.getFunctionValueAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMax(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Expm1 expm1_0 = new Expm1();
      assertNotNull(expm1_0);
      
      RegulaFalsiSolver regulaFalsiSolver0 = new RegulaFalsiSolver();
      assertEquals(1.0E-15, regulaFalsiSolver0.getFunctionValueAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMin(), 0.01);
      assertEquals(1.0E-6, regulaFalsiSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(1.0E-14, regulaFalsiSolver0.getRelativeAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMax(), 0.01);
      assertNotNull(regulaFalsiSolver0);
      
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      double double0 = UnivariateSolverUtils.forceSide(443, expm1_0, regulaFalsiSolver0, 0.0, 0.0, 3972.8696, allowedSolution0);
      assertEquals(1.0E-6, regulaFalsiSolver0.getMax(), 0.01);
      assertEquals(1.0E-15, regulaFalsiSolver0.getFunctionValueAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMin(), 0.01);
      assertEquals(1.0E-6, regulaFalsiSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(1.0E-14, regulaFalsiSolver0.getRelativeAccuracy(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UnivariateSolverUtils.verifySequence(Double.NaN, (-1547.0990198198679), (-779.0333902));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Rint rint0 = new Rint();
      assertNotNull(rint0);
      
      double double0 = UnivariateSolverUtils.solve((UnivariateFunction) rint0, 0.0, 165.6, 5.642533759462718E-305);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      double double0 = UnivariateSolverUtils.solve((UnivariateFunction) atanh0, 1.0303966192973381E-205, 2139.337, (-1295.74573));
      assertEquals(1.0303966192973381E-205, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = 0.5;
      doubleArray0[1] = (-1.440995270758115E-291);
      PolynomialFunctionLagrangeForm polynomialFunctionLagrangeForm0 = new PolynomialFunctionLagrangeForm(doubleArray0, doubleArray0);
      assertEquals(2, polynomialFunctionLagrangeForm0.degree());
      assertNotNull(polynomialFunctionLagrangeForm0);
      assertArrayEquals(new double[] {0.5, (-1.440995270758115E-291), 0.0}, doubleArray0, 0.01);
      assertEquals(3, doubleArray0.length);
      
      double double0 = UnivariateSolverUtils.solve((UnivariateFunction) polynomialFunctionLagrangeForm0, (-2846.26651826), 0.5, 0.5);
      assertEquals(2, polynomialFunctionLagrangeForm0.degree());
      assertArrayEquals(new double[] {0.5, (-1.440995270758115E-291), 0.0}, doubleArray0, 0.01);
      assertEquals((-9.992007221626409E-15), double0, 0.01);
      assertEquals(3, doubleArray0.length);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Tanh tanh0 = new Tanh();
      assertNotNull(tanh0);
      
      double double0 = UnivariateSolverUtils.solve((UnivariateFunction) tanh0, (-1220.67677285), (-2.9020908354550263E-153));
      assertEquals((-2.9020908354550263E-153), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      double double0 = UnivariateSolverUtils.midpoint(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      double double0 = UnivariateSolverUtils.midpoint(4, 1);
      assertEquals(2.5, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Logit logit0 = new Logit();
      assertNotNull(logit0);
      
      RegulaFalsiSolver regulaFalsiSolver0 = new RegulaFalsiSolver(224.863872306);
      assertEquals(0.0, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMax(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMin(), 0.01);
      assertEquals(1.0E-14, regulaFalsiSolver0.getRelativeAccuracy(), 0.01);
      assertEquals(224.863872306, regulaFalsiSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(1.0E-15, regulaFalsiSolver0.getFunctionValueAccuracy(), 0.01);
      assertNotNull(regulaFalsiSolver0);
      
      AllowedSolution allowedSolution0 = AllowedSolution.ANY_SIDE;
      double double0 = UnivariateSolverUtils.forceSide((-94), logit0, regulaFalsiSolver0, (-875.983), (-94), (-94), allowedSolution0);
      assertEquals(0.0, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMax(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMin(), 0.01);
      assertEquals(1.0E-14, regulaFalsiSolver0.getRelativeAccuracy(), 0.01);
      assertEquals(224.863872306, regulaFalsiSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(1.0E-15, regulaFalsiSolver0.getFunctionValueAccuracy(), 0.01);
      assertEquals((-875.983), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      double[] doubleArray0 = UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, (-293.971), (-891.0106), 274.61);
      assertNotNull(doubleArray0);
      assertArrayEquals(new double[] {(-0.9710000000000036), 0.028999999999996362}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Cosh cosh0 = new Cosh();
      assertNotNull(cosh0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.verifyBracketing(cosh0, (-977.9999993805901), (-977.9999993805901));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [-978, -978]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Cos cos0 = new Cos();
      assertNotNull(cos0);
      
      // Undeclared exception!
      UnivariateSolverUtils.solve((UnivariateFunction) cos0, (-420.03402061435), (double) 1003734400, (-1095.0));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Sinc sinc0 = new Sinc();
      assertNotNull(sinc0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.solve((UnivariateFunction) sinc0, 751.271807, 751.271807, 809.0340385215716);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [751.272, 751.272]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Cos cos0 = new Cos();
      assertNotNull(cos0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.solve((UnivariateFunction) cos0, 0.5, 0.5);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [0.5, 0.5]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Logit logit0 = new Logit();
      assertNotNull(logit0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.isBracketing(logit0, 443, Double.NaN);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 443 out of [0, 1] range
         //
         verifyException("org.apache.commons.math4.analysis.function.Logit", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      try { 
        UnivariateSolverUtils.isBracketing((UnivariateFunction) null, 1408.768, 1074.2496);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      RegulaFalsiSolver regulaFalsiSolver0 = new RegulaFalsiSolver(2289.38794, (-1.0), (-629.4276999986276));
      assertEquals((-629.4276999986276), regulaFalsiSolver0.getFunctionValueAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMax(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMin(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals((-1.0), regulaFalsiSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(2289.38794, regulaFalsiSolver0.getRelativeAccuracy(), 0.01);
      assertNotNull(regulaFalsiSolver0);
      
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.forceSide(3, inverse0, regulaFalsiSolver0, (-617.4276999986276), (-1.145810806477298E-8), 0.40808206181339196, allowedSolution0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // illegal state: maximal count (1) exceeded: evaluations
         //
         verifyException("org.apache.commons.math4.analysis.solvers.BaseAbstractUnivariateSolver", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      BracketingNthOrderBrentSolver bracketingNthOrderBrentSolver0 = new BracketingNthOrderBrentSolver(0.5, 0.5, Integer.MAX_VALUE, Integer.MAX_VALUE);
      assertEquals(0.0, bracketingNthOrderBrentSolver0.getMin(), 0.01);
      assertEquals(0.5, bracketingNthOrderBrentSolver0.getRelativeAccuracy(), 0.01);
      assertEquals(0.0, bracketingNthOrderBrentSolver0.getMax(), 0.01);
      assertEquals(2.147483647E9, bracketingNthOrderBrentSolver0.getFunctionValueAccuracy(), 0.01);
      assertEquals(0.5, bracketingNthOrderBrentSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(0.0, bracketingNthOrderBrentSolver0.getStartValue(), 0.01);
      assertEquals(Integer.MAX_VALUE, bracketingNthOrderBrentSolver0.getMaximalOrder());
      assertNotNull(bracketingNthOrderBrentSolver0);
      
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.forceSide(Integer.MAX_VALUE, inverse0, bracketingNthOrderBrentSolver0, (-3.5966064858620067E-8), 0.5, (-1.0), allowedSolution0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.analysis.solvers.BracketingNthOrderBrentSolver", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Logit logit0 = new Logit();
      assertNotNull(logit0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) logit0, (double) 426, (double) 426, (double) 426, 426);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [426, 426]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) inverse0, (double) 807, 810.960120108807, (double) 807, (double) 807, 810.960120108807, 807);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [810.96, 807]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) null, 2075.44983067, 2075.44983067, 2804.84711763);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      try { 
        UnivariateSolverUtils.verifyInterval(184.0, 184.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [184, 184]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      UnivariateSolverUtils.verifyInterval(Double.NaN, Double.NaN);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Sigmoid sigmoid0 = new Sigmoid();
      assertNotNull(sigmoid0);
      
      boolean boolean0 = UnivariateSolverUtils.isBracketing(sigmoid0, 1802.97032148059, 1802.97032148059);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      boolean boolean0 = UnivariateSolverUtils.isBracketing(inverse0, (-152.9936986332449), 0.5);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Cbrt cbrt0 = new Cbrt();
      assertNotNull(cbrt0);
      
      boolean boolean0 = UnivariateSolverUtils.isBracketing(cbrt0, (-1743.828), (-1743.828));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Cbrt cbrt0 = new Cbrt();
      assertNotNull(cbrt0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) cbrt0, 798.0, (-4.4156343103298585E-9), (double) 807, (double) 807, Double.NaN, 1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [\uFFFD, \uFFFD], values: [\uFFFD, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, (-281.97026778), (-281.97026778), (-1.0), 0.5, (-1.0), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // bad value for maximum iterations number: 0
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) null, 175.6735433253477, 175.6735433253477, 175.6735433253477, (-485.554998), (-485.554998), 715);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      try { 
        UnivariateSolverUtils.verifySequence(1.0E-15, 1.0E-15, 714.2335034436156);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [0, 0]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      try { 
        UnivariateSolverUtils.verifyBracketing((UnivariateFunction) null, 0, 1665.093622759217);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      boolean boolean0 = UnivariateSolverUtils.isSequence(429.63503, 1590.8246, 537.588835750331);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      boolean boolean0 = UnivariateSolverUtils.isSequence((-568.873689496734), (-1.0), 880.94534);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      boolean boolean0 = UnivariateSolverUtils.isSequence(880.94534, 0.0, 0.0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Cosh cosh0 = new Cosh();
      assertNotNull(cosh0);
      
      try { 
        UnivariateSolverUtils.verifyBracketing(cosh0, 20.0, 592.3597274101212);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [20, 592.36], values: [242,582,597.705, 90,684,052,619,679,880,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Cos cos0 = new Cos();
      assertNotNull(cos0);
      
      boolean boolean0 = UnivariateSolverUtils.isBracketing(cos0, (-5862.2), 1855.535501919);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      UnivariateSolverUtils.verifyBracketing(inverse0, (-1724.7996764987502), 787.8864740574304);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Acos acos0 = new Acos();
      assertNotNull(acos0);
      
      try { 
        UnivariateSolverUtils.verifyBracketing(acos0, 1.0, Double.NaN);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [1, \uFFFD], values: [0, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      double[] doubleArray0 = UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, (-12.728018442796614), (-138.190130374089), 1200.656678043, 1366);
      assertNotNull(doubleArray0);
      assertArrayEquals(new double[] {(-0.7280184427966141), 0.2719815572033859}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      double[] doubleArray0 = UnivariateSolverUtils.bracket((UnivariateFunction) inverse0, 1.0, (-1077.0052), (double) 807, 807);
      assertNotNull(doubleArray0);
      assertArrayEquals(new double[] {(-1.0), 0.0}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      double[] doubleArray0 = UnivariateSolverUtils.bracket((UnivariateFunction) inverse0, 7.0, (-2678.8971225647333), 755.0324885853594, (double) 1366, (-1.0), 1366);
      assertNotNull(doubleArray0);
      assertArrayEquals(new double[] {(-1359.0), 755.0324885853594}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, 3376.823381580903, (-1.0), 3.002095574584687E155, 1.7602040767669678, (-127.765), 1366);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [-1, 31,887.078], values: [-\u221E, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) inverse0, (double) 807, 2.993183789477209E-192, 809.0340385215716, 807);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [0, 809.034], values: [334,092,414,744,321,600,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000, 0.001]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Logit logit0 = new Logit();
      assertNotNull(logit0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) logit0, 809.0340385215716, 809.0340385215716, 809.0340385215716, (-365));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // bad value for maximum iterations number: -365
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Ceil ceil0 = new Ceil();
      assertNotNull(ceil0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) ceil0, (-774.187), (-774.187), (-1746.0993529975), (-774.187), (-1746.0993529975), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -774.187 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      RegulaFalsiSolver regulaFalsiSolver0 = new RegulaFalsiSolver(516.5511129264185, 20.0, 516.5511129264185);
      assertEquals(516.5511129264185, regulaFalsiSolver0.getRelativeAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMax(), 0.01);
      assertEquals(20.0, regulaFalsiSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getMin(), 0.01);
      assertEquals(0.0, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals(516.5511129264185, regulaFalsiSolver0.getFunctionValueAccuracy(), 0.01);
      assertNotNull(regulaFalsiSolver0);
      
      AllowedSolution allowedSolution0 = AllowedSolution.RIGHT_SIDE;
      try { 
        UnivariateSolverUtils.forceSide(1653, inverse0, regulaFalsiSolver0, (-3500.600367322789), (-576.6440526859524), (-160.18965448904135), allowedSolution0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // number of iterations=1,653, maximum iterations=1,653, initial=-3,500.6, lower bound=-576.644, upper bound=-160.19, final a value=-576.644, final b value=-160.19, f(a)=-0.002, f(b)=-0.006
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      PegasusSolver pegasusSolver0 = new PegasusSolver(2.993183789477209E-192, 2.993183789477209E-192);
      assertEquals(0.0, pegasusSolver0.getStartValue(), 0.01);
      assertEquals(1.0E-15, pegasusSolver0.getFunctionValueAccuracy(), 0.01);
      assertEquals(2.993183789477209E-192, pegasusSolver0.getAbsoluteAccuracy(), 0.01);
      assertEquals(0.0, pegasusSolver0.getMin(), 0.01);
      assertEquals(0.0, pegasusSolver0.getMax(), 0.01);
      assertEquals(2.993183789477209E-192, pegasusSolver0.getRelativeAccuracy(), 0.01);
      assertNotNull(pegasusSolver0);
      
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      try { 
        UnivariateSolverUtils.forceSide(807, inverse0, pegasusSolver0, (-1722.7996764987502), (-1722.7996764987502), 2.993183789477209E-192, allowedSolution0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // number of iterations=808, maximum iterations=807, initial=-1,722.8, lower bound=-1,722.8, upper bound=0, final a value=-1,722.8, final b value=-1,722.8, f(a)=-0.001, f(b)=-0.001
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      BracketingNthOrderBrentSolver bracketingNthOrderBrentSolver0 = new BracketingNthOrderBrentSolver(0.5, 0.5, Integer.MAX_VALUE, Integer.MAX_VALUE);
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      // Undeclared exception!
      UnivariateSolverUtils.forceSide(Integer.MAX_VALUE, inverse0, bracketingNthOrderBrentSolver0, 0.606, 0.5, Integer.MAX_VALUE, allowedSolution0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      BracketingNthOrderBrentSolver bracketingNthOrderBrentSolver0 = new BracketingNthOrderBrentSolver((-380.483), (-380.483), Integer.MAX_VALUE, Integer.MAX_VALUE);
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      // Undeclared exception!
      UnivariateSolverUtils.forceSide(Integer.MAX_VALUE, inverse0, bracketingNthOrderBrentSolver0, (-3480.291862143394), (-281.97026778), (-3480.291862143394), allowedSolution0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      BracketingNthOrderBrentSolver bracketingNthOrderBrentSolver0 = new BracketingNthOrderBrentSolver();
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.forceSide(Integer.MAX_VALUE, inverse0, bracketingNthOrderBrentSolver0, (-9.562359795632425), Integer.MAX_VALUE, 0.606, allowedSolution0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [2,147,483,647, -9.562]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      RegulaFalsiSolver regulaFalsiSolver0 = new RegulaFalsiSolver((-281.97026778), (-10.510268653601976), (-281.97026778));
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      double double0 = UnivariateSolverUtils.forceSide(1366, atanh0, regulaFalsiSolver0, 2.9676011119845104E-8, (-10.510268653601976), 0.0, allowedSolution0);
      assertEquals(2.9676011119845104E-8, regulaFalsiSolver0.getStartValue(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      RegulaFalsiSolver regulaFalsiSolver0 = new RegulaFalsiSolver();
      try { 
        UnivariateSolverUtils.forceSide(807, inverse0, regulaFalsiSolver0, 2618.60154623, 807, 807, allowedSolution0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // number of iterations=807, maximum iterations=807, initial=2,618.602, lower bound=807, upper bound=807, final a value=2,618.601, final b value=807, f(a)=0, f(b)=0.001
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Cos cos0 = new Cos();
      RegulaFalsiSolver regulaFalsiSolver0 = new RegulaFalsiSolver(754.6466, 224, 224);
      AllowedSolution allowedSolution0 = AllowedSolution.ANY_SIDE;
      double double0 = UnivariateSolverUtils.forceSide(224, cos0, regulaFalsiSolver0, 754.6466, 754.6466, (-364.062911749959), allowedSolution0);
      assertEquals(754.6466, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Logit logit0 = new Logit();
      AllowedSolution allowedSolution0 = AllowedSolution.ABOVE_SIDE;
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.forceSide(208, logit0, (BracketedUnivariateSolver<UnivariateFunction>) null, 426, (-762.2), (-762.2), allowedSolution0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      try { 
        UnivariateSolverUtils.solve((UnivariateFunction) null, (double) Integer.MAX_VALUE, 1.65748157925005E114, 3203.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      try { 
        UnivariateSolverUtils.solve((UnivariateFunction) null, 173.66664055773612, (-1463.27));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      double double0 = UnivariateSolverUtils.midpoint((-999.49377276), 0.5);
      assertEquals((-499.49688638), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Cos cos0 = new Cos();
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) cos0, 2474.0, 14.0, 1921.649212);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [2,474, 1,921.649]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
  }

@Test
  public void test04_pred1()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, (-872.79967649875), (-1746.0993529975), (-561.6440526859524));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [-1,746.099, -561.644], values: [\uFFFD, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test05_pred2()  throws Throwable  {
      Cbrt cbrt0 = new Cbrt();
      assertNotNull(cbrt0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) cbrt0, Double.NaN, (double) 1, Double.NaN, (double) 1, Double.NaN, 1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [\uFFFD, \uFFFD], values: [\uFFFD, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test06_pred3()  throws Throwable  {
      double[] doubleArray0 = new double[2];
      PolynomialFunction polynomialFunction0 = new PolynomialFunction(doubleArray0);
      assertEquals(0, polynomialFunction0.degree());
      assertNotNull(polynomialFunction0);
      assertArrayEquals(new double[] {0.0, 0.0}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) polynomialFunction0, 932.0102211, 537.588835750331, (-2273.30145656), 0.0, 0.0, 986);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 0 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test17_pred4()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      double[] doubleArray0 = UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, (-293.971), (-891.0106), 274.61);
      assertNotNull(doubleArray0);
      assertArrayEquals(new double[] {(-0.9710000000000036), 0.028999999999996362}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
}

@Test
  public void test26_pred5()  throws Throwable  {
      Logit logit0 = new Logit();
      assertNotNull(logit0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) logit0, (double) 426, (double) 426, (double) 426, 426);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [426, 426]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test27_pred6()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) inverse0, (double) 807, 810.960120108807, (double) 807, (double) 807, 810.960120108807, 807);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [810.96, 807]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test28_pred7()  throws Throwable  {
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) null, 2075.44983067, 2075.44983067, 2804.84711763);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test34_pred8()  throws Throwable  {
      Cbrt cbrt0 = new Cbrt();
      assertNotNull(cbrt0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) cbrt0, 798.0, (-4.4156343103298585E-9), (double) 807, (double) 807, Double.NaN, 1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [\uFFFD, \uFFFD], values: [\uFFFD, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test35_pred9()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, (-281.97026778), (-281.97026778), (-1.0), 0.5, (-1.0), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // bad value for maximum iterations number: 0
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test36_pred10()  throws Throwable  {
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) null, 175.6735433253477, 175.6735433253477, 175.6735433253477, (-485.554998), (-485.554998), 715);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test46_pred11()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      double[] doubleArray0 = UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, (-12.728018442796614), (-138.190130374089), 1200.656678043, 1366);
      assertNotNull(doubleArray0);
      assertArrayEquals(new double[] {(-0.7280184427966141), 0.2719815572033859}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
}

@Test
  public void test47_pred12()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      double[] doubleArray0 = UnivariateSolverUtils.bracket((UnivariateFunction) inverse0, 1.0, (-1077.0052), (double) 807, 807);
      assertNotNull(doubleArray0);
      assertArrayEquals(new double[] {(-1.0), 0.0}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
}

@Test
  public void test48_pred13()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      double[] doubleArray0 = UnivariateSolverUtils.bracket((UnivariateFunction) inverse0, 7.0, (-2678.8971225647333), 755.0324885853594, (double) 1366, (-1.0), 1366);
      assertNotNull(doubleArray0);
      assertArrayEquals(new double[] {(-1359.0), 755.0324885853594}, doubleArray0, 0.01);
      assertEquals(2, doubleArray0.length);
}

@Test
  public void test49_pred14()  throws Throwable  {
      Atanh atanh0 = new Atanh();
      assertNotNull(atanh0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) atanh0, 3376.823381580903, (-1.0), 3.002095574584687E155, 1.7602040767669678, (-127.765), 1366);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [-1, 31,887.078], values: [-\u221E, \uFFFD]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test50_pred15()  throws Throwable  {
      Inverse inverse0 = new Inverse();
      assertNotNull(inverse0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) inverse0, (double) 807, 2.993183789477209E-192, 809.0340385215716, 807);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // function values at endpoints do not have different signs, endpoints: [0, 809.034], values: [334,092,414,744,321,600,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000, 0.001]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test51_pred16()  throws Throwable  {
      Logit logit0 = new Logit();
      assertNotNull(logit0);
      
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) logit0, 809.0340385215716, 809.0340385215716, 809.0340385215716, (-365));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // bad value for maximum iterations number: -365
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test52_pred17()  throws Throwable  {
      Ceil ceil0 = new Ceil();
      assertNotNull(ceil0);
      
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) ceil0, (-774.187), (-774.187), (-1746.0993529975), (-774.187), (-1746.0993529975), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -774.187 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}

@Test
  public void test65_pred18()  throws Throwable  {
      Cos cos0 = new Cos();
      // Undeclared exception!
      try { 
        UnivariateSolverUtils.bracket((UnivariateFunction) cos0, 2474.0, 14.0, 1921.649212);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // endpoints do not specify an interval: [2,474, 1,921.649]
         //
         verifyException("org.apache.commons.math4.analysis.solvers.UnivariateSolverUtils", e);
      }
}
}