/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 16 10:09:08 GMT 2025
 */

package org.apache.commons.math4.random;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import org.apache.commons.math4.random.EmpiricalDistribution;
import org.apache.commons.math4.random.ISAACRandom;
import org.apache.commons.math4.random.JDKRandomGenerator;
import org.apache.commons.math4.random.RandomGenerator;
import org.apache.commons.math4.random.Well512a;
import org.apache.commons.math4.stat.descriptive.SummaryStatistics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EmpiricalDistribution_ESTest extends EmpiricalDistribution_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      // Undeclared exception!
      try { 
        empiricalDistribution0.inverseCumulativeProbability(Double.NaN);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      assertFalse(empiricalDistribution0.isLoaded());
      
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.cumulativeProbability(1000.0);
      assertEquals(1.0, double0, 0.01);
  }

//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//      File file0 = MockFile.createTempFile("b9s&bx$", "47q,]KwIRSGkst", (File) null);
//      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(1, (RandomGenerator) null);
//      assertFalse(empiricalDistribution0.isLoaded());
//
//      empiricalDistribution0.load(file0);
//      empiricalDistribution0.getGeneratorUpperBounds();
//      assertTrue(empiricalDistribution0.isLoaded());
//  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      
      double[] doubleArray0 = new double[2];
      empiricalDistribution0.load(doubleArray0);
      empiricalDistribution0.isLoaded();
      assertEquals(0.0, empiricalDistribution0.getSupportUpperBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[1];
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.inverseCumulativeProbability(1.0);
      assertEquals(0.0, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      assertFalse(empiricalDistribution0.isLoaded());
      
      double[] doubleArray0 = new double[14];
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getSupportUpperBound();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      double[] doubleArray0 = new double[2];
      doubleArray0[0] = 1.0E-6;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getSupportUpperBound();
      assertEquals(1.0E-6, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[1];
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getSupportLowerBound();
      assertEquals(0.0, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[1];
      doubleArray0[0] = (-307.868242);
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getSupportLowerBound();
      assertEquals((-307.868242), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(2817);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      
      double[] doubleArray0 = new double[0];
      empiricalDistribution0.load(doubleArray0);
      empiricalDistribution0.getSampleStats();
      assertEquals(2817, empiricalDistribution0.getBinCount());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(1695);
      double[] doubleArray0 = new double[4];
      empiricalDistribution0.load(doubleArray0);
      empiricalDistribution0.getSampleStats();
      assertEquals(0.0, empiricalDistribution0.getSupportUpperBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      assertFalse(empiricalDistribution0.isLoaded());
      
      double[] doubleArray0 = new double[1];
      empiricalDistribution0.load(doubleArray0);
      empiricalDistribution0.getNumericalVariance();
      assertEquals(1000, empiricalDistribution0.getBinCount());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getNumericalVariance();
      assertEquals(1000.0, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(333333.3333333333, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      double[] doubleArray0 = new double[2];
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getNumericalMean();
      assertEquals(0.0, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getNumericalMean();
      assertEquals(1000.0, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(333.33333333333337, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[6];
      doubleArray0[0] = (double) (-2496L);
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getNumericalMean();
      assertEquals(0.0, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals((-416.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[1];
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.getNextValue();
      assertEquals(0.0, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      double[] doubleArray0 = new double[1];
      doubleArray0[0] = 1.0E-6;
      empiricalDistribution0.load(doubleArray0);
      assertTrue(empiricalDistribution0.isLoaded());
      
      double double0 = empiricalDistribution0.getNextValue();
      assertEquals(1.0E-6, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      SummaryStatistics summaryStatistics0 = new SummaryStatistics();
      summaryStatistics0.addValue((-1221.344665));
      empiricalDistribution0.getKernel(summaryStatistics0);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      SummaryStatistics summaryStatistics0 = new SummaryStatistics();
      summaryStatistics0.addValue(0.58670545F);
      empiricalDistribution0.getKernel(summaryStatistics0);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      SummaryStatistics summaryStatistics0 = new SummaryStatistics();
      empiricalDistribution0.getKernel(summaryStatistics0);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      double[] doubleArray0 = new double[3];
      empiricalDistribution0.load(doubleArray0);
      empiricalDistribution0.getBinStats();
      assertTrue(empiricalDistribution0.isLoaded());
      assertEquals(0.0, empiricalDistribution0.getSupportUpperBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution((-3063));
      int int0 = empiricalDistribution0.getBinCount();
      assertEquals((-3063), int0);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      assertFalse(empiricalDistribution0.isLoaded());
      
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.density(1000.0);
      assertEquals(0.0, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(0.5, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      try { 
        empiricalDistribution0.load((double[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution((-2377));
      // Undeclared exception!
      try { 
        empiricalDistribution0.load(doubleArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(0);
      double[] doubleArray0 = new double[0];
      // Undeclared exception!
      try { 
        empiricalDistribution0.load(doubleArray0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution((-48));
      double[] doubleArray0 = new double[20];
      // Undeclared exception!
      try { 
        empiricalDistribution0.load(doubleArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      try { 
        empiricalDistribution0.load((URL) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      URL uRL0 = MockURL.getFileExample();
      // Undeclared exception!
      try { 
        empiricalDistribution0.load(uRL0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.net.URL", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      URL uRL0 = MockURL.getHttpExample();
      try { 
        empiricalDistribution0.load(uRL0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Could not find: www.someFakeButWellFormedURL.org
         //
         verifyException("org.evosuite.runtime.mock.java.net.EvoHttpURLConnection", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      try { 
        empiricalDistribution0.load((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // null is not allowed
         //
         verifyException("org.apache.commons.math4.util.MathUtils", e);
      }
  }

//  @Test(timeout = 4000)
//  public void test32()  throws Throwable  {
//      File file0 = MockFile.createTempFile("org.apache.commons.math4.random.EmpiricalDistribution$1", "org.apache.commons.math4.random.EmpiricalDistribution$1");
//      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution((-207));
//      // Undeclared exception!
//      try {
//        empiricalDistribution0.load(file0);
//        fail("Expecting exception: NegativeArraySizeException");
//
//      } catch(NegativeArraySizeException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
//      }
//  }

//  @Test(timeout = 4000)
//  public void test33()  throws Throwable  {
//      JDKRandomGenerator jDKRandomGenerator0 = new JDKRandomGenerator();
//      File file0 = MockFile.createTempFile("P%mZSo.BPSi<_B+O-", "P%mZSo.BPSi<_B+O-");
//      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(0, jDKRandomGenerator0);
//      // Undeclared exception!
//      try {
//        empiricalDistribution0.load(file0);
//        fail("Expecting exception: IndexOutOfBoundsException");
//
//      } catch(IndexOutOfBoundsException e) {
//         //
//         // Index: 0, Size: 0
//         //
//         verifyException("java.util.ArrayList", e);
//      }
//  }

//  @Test(timeout = 4000)
//  public void test34()  throws Throwable  {
//      File file0 = MockFile.createTempFile(":0YSs", ":0YSs");
//      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp/:0YSs0:0YSs");
//      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
//      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
//      try {
//        empiricalDistribution0.load(file0);
//        fail("Expecting exception: IOException");
//
//      } catch(IOException e) {
//         //
//         // Simulated IOException
//         //
//         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
//      }
//  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      MockFile mockFile0 = new MockFile("");
      try { 
        empiricalDistribution0.load((File) mockFile0);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[2];
      empiricalDistribution0.load(doubleArray0);
      // Undeclared exception!
      try { 
        empiricalDistribution0.inverseCumulativeProbability(1.0E-6);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // standard deviation (0)
         //
         verifyException("org.apache.commons.math4.distribution.NormalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution((-4879));
      // Undeclared exception!
      try { 
        empiricalDistribution0.getUpperBounds();
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

//  @Test(timeout = 4000)
//  public void test38()  throws Throwable  {
//      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(1901);
//      MockFile mockFile0 = new MockFile("");
//      File file0 = MockFile.createTempFile("ct;`>C$4.Tl9fq$", "number of polynomial interpolants must match the number of segments ({0} != {1} - 1)", (File) mockFile0);
//      empiricalDistribution0.load(file0);
//      empiricalDistribution0.getNextValue();
//      empiricalDistribution0.getNextValue();
//      // Undeclared exception!
//      empiricalDistribution0.getNextValue();
//  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Well512a well512a0 = new Well512a();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(well512a0);
      // Undeclared exception!
      try { 
        empiricalDistribution0.getKernel((SummaryStatistics) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[7];
      doubleArray0[1] = (double) 1000;
      doubleArray0[2] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      // Undeclared exception!
      try { 
        empiricalDistribution0.density(1000.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // standard deviation (0)
         //
         verifyException("org.apache.commons.math4.distribution.NormalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      // Undeclared exception!
      try { 
        empiricalDistribution0.density(Double.NaN);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution((-4660));
      // Undeclared exception!
      try { 
        empiricalDistribution0.density(Double.NaN);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 1000;
      doubleArray0[1] = 1.0E-6;
      doubleArray0[2] = 1.0E-6;
      empiricalDistribution0.load(doubleArray0);
      // Undeclared exception!
      try { 
        empiricalDistribution0.cumulativeProbability(1.0E-6);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // standard deviation (0)
         //
         verifyException("org.apache.commons.math4.distribution.NormalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution((-1167));
      // Undeclared exception!
      try { 
        empiricalDistribution0.cumulativeProbability(Double.NaN);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = empiricalDistribution0.getUpperBounds();
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(1000, doubleArray0.length);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      assertFalse(empiricalDistribution0.isLoaded());
      
      double[] doubleArray0 = new double[0];
      empiricalDistribution0.load(doubleArray0);
      empiricalDistribution0.sample();
      assertEquals(1000, empiricalDistribution0.getBinCount());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(3779);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.sample();
      assertEquals(0.0, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(1000.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.inverseCumulativeProbability(1.0);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.inverseCumulativeProbability(0.0);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      try { 
        empiricalDistribution0.inverseCumulativeProbability(1000);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1,000 out of [0, 1] range
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      try { 
        empiricalDistribution0.inverseCumulativeProbability((-138.544458483271));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -138.544 out of [0, 1] range
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      
      double[] doubleArray0 = new double[4];
      doubleArray0[1] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.cumulativeProbability(361.1905743632);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.cumulativeProbability(Double.POSITIVE_INFINITY);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.cumulativeProbability(1.0E-6);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(0.0, double0, 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[0];
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.density(1000);
      assertTrue(empiricalDistribution0.isLoaded());
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.density(Double.POSITIVE_INFINITY);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(0.0, double0, 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertFalse(empiricalDistribution0.isLoaded());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.density(1000);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(0.0, double0, 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      try { 
        empiricalDistribution0.getNextValue();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // distribution not loaded
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(2);
      double[] doubleArray0 = new double[17];
      empiricalDistribution0.load(doubleArray0);
      // Undeclared exception!
      try { 
        empiricalDistribution0.getNextValue();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // standard deviation (0)
         //
         verifyException("org.apache.commons.math4.distribution.NormalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      assertFalse(empiricalDistribution0.isLoaded());
      
      double[] doubleArray0 = new double[0];
      empiricalDistribution0.load(doubleArray0);
      empiricalDistribution0.load(doubleArray0);
      assertTrue(empiricalDistribution0.isLoaded());
  }

//  @Test(timeout = 4000)
//  public void test61()  throws Throwable  {
//      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
//      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp/ 1dY0 1dY");
//      FileSystemHandling.appendStringToFile(evoSuiteFile0, "^G~|5");
//      File file0 = MockFile.createTempFile(" 1dY", " 1dY");
//      // Undeclared exception!
//      try {
//        empiricalDistribution0.load(file0);
//        fail("Expecting exception: NumberFormatException");
//
//      } catch(NumberFormatException e) {
//      }
//  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[0];
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.cumulativeProbability(1000);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(2817);
      boolean boolean0 = empiricalDistribution0.isLoaded();
      assertFalse(boolean0);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(2817, empiricalDistribution0.getBinCount());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      // Undeclared exception!
      try { 
        empiricalDistribution0.getNumericalMean();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      boolean boolean0 = empiricalDistribution0.isSupportUpperBoundInclusive();
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertTrue(boolean0);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.getSupportLowerBound();
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      empiricalDistribution0.reseedRandomGenerator((-1L));
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      boolean boolean0 = empiricalDistribution0.isSupportLowerBoundInclusive();
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[1];
      empiricalDistribution0.load(doubleArray0);
      double[] doubleArray1 = empiricalDistribution0.getGeneratorUpperBounds();
      // Undeclared exception!
      empiricalDistribution0.load(doubleArray1);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      int int0 = empiricalDistribution0.getBinCount();
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(1000, int0);
      assertFalse(empiricalDistribution0.isLoaded());
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      empiricalDistribution0.getSampleStats();
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      // Undeclared exception!
      try { 
        empiricalDistribution0.getGeneratorUpperBounds();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      // Undeclared exception!
      try { 
        empiricalDistribution0.getNumericalVariance();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.getSupportUpperBound();
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.probability(1.0E-6);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(0.0, double0, 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(1000, empiricalDistribution0.getBinCount());
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      empiricalDistribution0.getBinStats();
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      boolean boolean0 = empiricalDistribution0.isSupportConnected();
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertTrue(boolean0);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(1000, empiricalDistribution0.getBinCount());
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      empiricalDistribution0.reSeed(1000);
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertFalse(empiricalDistribution0.isLoaded());
  }

@Test
  public void test01_pred1()  throws Throwable  {
      ISAACRandom iSAACRandom0 = new ISAACRandom();
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution(iSAACRandom0);
      assertFalse(empiricalDistribution0.isLoaded());
      
      double[] doubleArray0 = new double[2];
      doubleArray0[1] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.cumulativeProbability(1000.0);
      assertEquals(1.0, double0, 0.01);
    org.junit.Assert.assertTrue(empiricalDistribution0.isLoaded());

}

@Test
  public void test43_pred2()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = (double) 1000;
      doubleArray0[1] = 1.0E-6;
      doubleArray0[2] = 1.0E-6;
      empiricalDistribution0.load(doubleArray0);
      // Undeclared exception!
      try { 
        empiricalDistribution0.cumulativeProbability(1.0E-6);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // standard deviation (0)
         //
         verifyException("org.apache.commons.math4.distribution.NormalDistribution", e);
      }
}

@Test
  public void test44_pred3()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution((-1167));
      // Undeclared exception!
      try { 
        empiricalDistribution0.cumulativeProbability(Double.NaN);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.random.EmpiricalDistribution", e);
      }
}

@Test
  public void test52_pred4()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      
      double[] doubleArray0 = new double[4];
      doubleArray0[1] = (double) 1000;
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.cumulativeProbability(361.1905743632);
      assertEquals(Double.NaN, double0, 0.01);
}

@Test
  public void test53_pred5()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.cumulativeProbability(Double.POSITIVE_INFINITY);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(1.0, double0, 0.01);
//    org.junit.Assert.assertEquals(0, empiricalDistribution0.getBinCount());

}

@Test
  public void test54_pred6()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double double0 = empiricalDistribution0.cumulativeProbability(1.0E-6);
      assertFalse(empiricalDistribution0.isLoaded());
      assertEquals(0.0, double0, 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, empiricalDistribution0.getSupportUpperBound(), 0.01);
      assertEquals(1000, empiricalDistribution0.getBinCount());
      assertEquals(Double.POSITIVE_INFINITY, empiricalDistribution0.getSupportLowerBound(), 0.01);
//    org.junit.Assert.assertTrue(empiricalDistribution0.isLoaded());

}

@Test
  public void test62_pred7()  throws Throwable  {
      EmpiricalDistribution empiricalDistribution0 = new EmpiricalDistribution();
      double[] doubleArray0 = new double[0];
      empiricalDistribution0.load(doubleArray0);
      double double0 = empiricalDistribution0.cumulativeProbability(1000);
      assertEquals(Double.NaN, double0, 0.01);
}
}